### ISSUE TITLE
fill.NAs has problems ignoring response when response is compound

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#100]
>   m <- lm(cost + t1 ~ cap + pr, data=nuclearplants)
    >   d <- model.frame(m)
    >   fill.NAs(d)
    Error in eval(expr, envir, enclos) : object 't1' not found

I believe this is due to `x <- as.formula(paste("~. -", response))` in fill.NAs. When `response` has a `+` in it, later in the function, `cost` and `t1` are independently looked for in `d`, when only `"cost + t1"` exists.

**Comment by josherrickson** [comment]
I've submitted a fix into branch fill.NAs.response.fix, just wanted to run it by @markmfredrickson to ensure it doesn't have any unintended consequences.

**Comment by benthestatistician** [comment]
I like [@josherrickson's fix for this issue](https://github.com/markmfredrickson/optmatch/commit/d98fa022b5f20bdd5c3e2f8dc78a0df42160671c).  I'll be interested to hear @markmfredrickson's take too.

**Comment by josherrickson** [comment]
Just noting that this is in master (d98fa022), I needed the fix for some of other recent work.

**Comment by markmfredrickson** [comment]
Might be good to have a test case with `cbind(a, b) ~ x`, as that is a formula we're likely to encounter if someone is doing a grouped logistic regression. Otherwise, looks good.

**Comment by benthestatistician** [comment]
Good catch, Mark. +1

On Fri, Jun 19, 2015 at 12:45 PM, Mark Fredrickson <notifications@github.com

**Comment by josherrickson** [comment]
Looks like this does not work. Issue is unrelated to my fix above.

The problem is that `model.frame(lm(cbind(a,b) ~ c))` is dimension `n x 2`, not `n x 3` - apparently a `data.frame` can include a `matrix` as a single "column".

I'll work on fixing this over the next few days.

**Comment by josherrickson** [comment]
The issue with `cbind` is larger than I anticipated. Seeing no blocks to the fix that opened this issue, closing to open a fresh issue for `cbind`.
