### ISSUE TITLE
"could not find function 'strata' " error

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#105]
I'm seeing

``` r
 fullmatch(pr~cap+strata(pt), data=nuclearplants)
## Error in eval(expr, envir, enclos) : could not find function "strata"
```

in optmatch 0.9-5.  Manually attaching the survival package to the search path fixes the problem, but of course this shouldn't be necessary.

I do see that    
- file `DESCRIPTION.template` lists survival in Depends field, if not in Imports field
- file  `NAMESPACE.static` has a line reading `importFrom(survival, strata)`, which differs from other lines in not quoting its arguments (e.g., `importFrom("digest", "digest")`).

No time to investigate further at the moment - in particular, no chance to see whether there's a quick fix based on one of the above.

**Comment by benthestatistician** [comment]
Assigning to you, @markmfredrickson, since you touched the above two lines most recently.

**Comment by markmfredrickson** [comment]
Grr. I thought depending brought strata into the user's search path.

**Comment by benthestatistician** [comment]
Hmm, Now I'm finding that I can't reproduce the problem; I'm getting:
```{r}
> library(optmatch)
Loading required package: survival
Loading required package: splines
The optmatch package has an academic license. Enter relaxinfo() for more information.
```
As @markmfredrickson would have expected.  

Conjecture as to what happened when I filed the bug: I had started my session and done `library(optmatch)`, then checked and realized I was using optmatch 0.9-3, and so updated to 0.9-5 and reloaded.  Somewhere in this sequence i suspect the survival dependency wasn't properly registered, it being new as of optmatch 0.9-5.  

The lack of quotes in the corresponding NAMESPACE.static line, `importsFrom(survival, strata)`, was still bugging me.  Encouraged by Wickham's discussion of non-standard evaluation in Advanced R, I indulge this bit of peevishness in f6e45c3.  

Closing the issue, but if somebody finds the same bug to arise in some less edge-casey context, do reopen and explain.

**Comment by benthestatistician** [comment]
A similar issue arose for me just now:

```r
 formula(psm1)
#lateECMO ~ strata(VentType) + CenterVolume + CenterMortality + 
#    AgeDays + pH + PCO2 + IntubationToTimeOnHours + PedRESCUERS + 
#   PREP
# NULL
 is(psm1)
# [1] "glm"      "lm"       "oldClass"
within_PScaliper <- match_on(psm1, caliper=.2)
# Error in strata(VentType) : could not find function "strata"
```
The problem is deep down in `model.frame.default()`: 

```r
1: match_on(psm1, caliper = 0.2)
2: match_on.glm(psm1, caliper = 0.2)
3: scores(x, newdata = themf, ...)
4: model.frame(formula(object), data = newdata, na.action = na.pass)
5: model.frame.default(formula(object), data = newdata, na.action = na.pas
6: eval(predvars, data, env)
7: eval(predvars, data, env)
```
Actually `model.frame.default()` gets successfully invoked several times before the problematic invocation from within `scores()`.  A conjecture about is that the problem has to do with `scores()` 
passing a data frame in its formula slot, then w/ this data frame being re-cast within `model.frame.default` as a terms object, in the process gaining an association with the `namespace:stats` environment.

**Comment by benthestatistician** [comment]
Superseded by #196.
