### ISSUE TITLE
`[.optmatch` should drop matched distances attribute

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#107]
Whenever we subset an optmatch object, simply get rid of any "matched.distances" attribute.  This will circumvent some [mysterious performance hits when working with large optmatch objects](https://github.com/markmfredrickson/optmatchExperimental/issues/1). 

Let's do this **after** #106, or at least the part of it saying to make `summary.optmatch` robust to the optmatch object's not having a matched distances attribute.

**Comment by josherrickson** [comment]
Completed.
