### ISSUE TITLE
check if commented out old tests are still needed/should pass

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#108]
In working on getting devtools running, I came across a few older tests (from the tests that I converted to testthat) which I couldn't get to pass.

Since they're older and in the interest of moving forward, I commented them out. Mark, can you take a look and see whether any of them should still pass?

84ccc2e0

**Comment by benthestatistician** [comment]
I agree with @josherrickson's call in each case. Thanks, J. Closing.
