### ISSUE TITLE
document recently introduced uses of `strata()`

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#112]
- [x] Verify that putting `strata(foo)` into a PS formula now causes `match_on.glm` & company to impose exact matching on `foo`, as inserted into NEWS re v0.9-6 in 66493af.
- [x] Update the passage of the `match_on` docs pertaining to `strata()` to indicate that the exact matching will happen when `match_on` is passed a model that was fitted along with a `strata` term, as well as when the `x` passed to `match_on` is a formula.
- [x] Add examples of both usages to inst/examples/match_on.R
- [x] Also add a quick example or two to inst/examples/fullmatch.R,  inst/examples/pairmatch.R
- [x] If fullmatch examples only exemplifying one of the `strata()` usages, fullmatch docs details section should point the user to `match_on` docs for more examples. 
- [x] Ditto for pairmatch.
- [x] Update NEWS statement of this to point to one or more of these documentation files for examples

**Comment by josherrickson** [comment]
Confirming that `strata(foo)` and `exactMatch( y ~ foo)` are equivalent; e.g. [test.match_on.R#531](https://github.com/markmfredrickson/optmatch/blob/master/tests/testthat/test.match_on.R#L531).

**Comment by josherrickson** [comment]
Documentation updated.
