### ISSUE TITLE
Enable varwidth option for boxplot methods 

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#113]
User-facing UI for our boxplot methods suggests that they default to `varwidth=TRUE`, which they don't.  Passing a `varwidth=TRUE` doesn't help either.  It looks like a simple developer oversight in the code....

**Comment by benthestatistician** [comment]
Maybe 0a93ea0 suffices to fix the problem.  Remains to check that.

**Comment by josherrickson** [comment]
I code-reviewed this. Per offline discussion with Ben, we're not going to add formal unit tests at this time.
