### ISSUE TITLE
informative error/warning for calls to `caliper` within `match_on.formula`'s formula argument

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#114]
I heard from a user who was frustrated about the following not working for him:
```{r}
# stratify on state
em1 <- exactMatch(treatment ~ State, data = dat)

# create distance matrices within state
dist_date <- match_on(treatment ~ Date, data=dat, within = em1)

# run the match
fm_caliper <- fullmatch(treatment~ Date + 
              	Dem_Affiliation + Rep_Affiliation + caliper(dist_date, width = 10),
                data = dat, within = em1)
```
This seems a natural thing for the user to try.  We might look for it and steer them toward imposing the caliper onto an ISM to be passed as via the within argument.

**Comment by josherrickson** [comment]
How's this?

```{r}
> data(nuclearplants)
> m <- match_on(pr ~ cost, data=nuclearplants)
> m2 <- match_on(pr ~ t1 + caliper(m) + caliper(n), data=nuclearplants)
Error in match_on.formula(pr ~ t1 + caliper(m) + caliper(n), data = nuclearplants) (from match_on.R#279) : 
  Calipers should be applied via the `within=` argument.
	E.g. `within=caliper(m) + caliper(n)`
```

I'm not sure if the 2nd line there is more helpful than potentially confusing. Perhaps drop it and have a quick reference in the `fullmatch` and  `pairmatch` documentation?

I considered trying to handle the `caliper` call in the formula, but it doesn't even really make sense, so I'm not sure we should train users to do that.

**Comment by benthestatistician** [comment]
I think that's great, @josherrickson. +1 !

I think the second line is more likely to be helpful that not.  I'd keep it, and leave out the docs refs: it's natural to go check the docs if you're still confused, and it's not like our docs are all that great. I agree about not trying to handle `caliper` calls within those formulas.

An adjustment to consider, but only if the adjustment is small and easy: Before issuing error message, check to see whether user has provided a within argument.  If yes, then the error message might instead read:

```{r}
Error in match_on.formula(pr ~ t1 + caliper(m) + caliper(n), within=em, data = nuclearplants) (from match_on.R#279) : 
  Calipers should be applied via the `within=` argument.
    E.g. `within=caliper(m) + caliper(n) + em`
```
or even just
```{r}
Error in match_on.formula(pr ~ t1 + caliper(m) + caliper(n), within=em, data = nuclearplants) (from match_on.R#279) : 
  Calipers should be applied via the `within=` argument.
    E.g. `within=caliper(m) + caliper(n) + <...>`
```
Then I'd think this is ready for closing.

**Comment by josherrickson** [comment]
New version:

```{r}
> match_on(pr ~ t1 + caliper(m) + caliper(n), data=nuclearplants, within=em)
 Error in match_on.formula(pr ~ t1 + caliper(m) + caliper(n), data = nuclearplants,  : 
  Calipers should be applied via the `within=` argument instead of in the formula.
	E.g. `within = em + caliper(m) + caliper(n)` 
```

Closing.

**Comment by benthestatistician** [comment]
Great!
