### ISSUE TITLE
Should `pairmatch` replace infeasible subproblems with feasible ones? 

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#116]
Given a subclass with 3 treatments and 2 controls, `pairmatch` quits with an error. Even if you pass it the `remove.unmatchables=TRUE` flag. Maybe in the latter circumstance it should try to create 2 pairs, leaving one treatment group member unmatched, only quitting with an error if that can't be done given the constraints embedded in the distance.

**Comment by benthestatistician** [comment]
(Noting that this functionality would have been useful to @andy-zack.  We won't be able to do anything with it in time to be of use to him on that project, but perhaps future progress on this question would interest him anyway.)

**Comment by josherrickson** [comment]
I looked into this a bit.

I think the issue is actually in `fullmatch`, not `pairmatch`. Inside `.fullmatch.with.recovery`, if fullmatch with the original `max.controls` and `min.controls` fails, we fall back to trying with the same `min.controls` but `max.controls = Inf`.

This means that we get the following:

```{r}
> d <- data.frame(z = c(0,0,1,1,1),
+                 x = 1:5)
> fullmatch(z ~ x, data = d)
  1   2   3   4   5 
1.2 1.1 1.1 1.2 1.1 
> fullmatch(z ~ x, min = 1, data = d )
   1    2    3    4    5 
<NA> <NA> <NA> <NA> <NA> 
```
I believe it was a design choice to never drop treatment group members unless they are unmatchable, e.g.,

```{r}
> m <- match_on(z ~ x, data = d)
> m[1,] <- rep(NA, 2)
> fullmatch(m, min = 1, data = d)
   1    2    3    4    5 
 1.2  1.1 <NA>  1.1  1.2 
```

Its possible that the logic here should be different for `pair` and `full`, but its not immediately obvious how to enforce this. By the time `fullmatch` makes the attempted recovery, it doesn't know that this was originally a `pairmatch` call. Perhaps we need another flag, `drop.treatment.if.needed` or something like that?

**Comment by benthestatistician** [comment]
Thanks, @josherrickson .  More comments:

1.  You're right that not dropping treatment group members unless unmatchable was a design choice.  I'd like to revisit it.  The motivation for that choice came from thinking about single stratum problems; in multi-stratum problems it seems that one can lose a lot of treatment group members this way, and currently there's no direct way of limiting that loss of sample size. 
2. My ideal would be as follows.  If the user has specified `remove.unmatchables=TRUE`, then we not only excise unmatchable subjects but also try harder to arrange matches in each subproblem:  for each subproblem we'd first try to place every treatment member into a 1:1 pair, without sharing controls; if that can't be done, then before giving up we try to place every control group member into a 1:1 pair (without sharing treatments).  We only give up and return NA for everyone if both of these fail.
3.  As an aside, there's no substantive need to attempt infeasibility recovery for a pair match that was found to be infeasible. We could just as well declare it infeasible and keep moving.  (I understand that there may be other reasons, such as tidiness of the codebase, to do this, just point it out while we're on the topic.)

**Comment by benthestatistician** [comment]
In earlier versions of optmatch that supported `fullmatch` with a negative "omit.controls" argument, one could write `omit.controls=-.5` to mean "match all of the controls to half of the treatment group."  We're not supporting that at the moment (cf #77), but if we were to re-enable such support then we could get the feature described in this issue after a few straightforward modifications of `pairmatch.matrix`. 

Additional comments:

1.  Toward the end of `pairmatch.matrix` we temporarily fiddle with the "fullmatch_try_recovery" option, turning it to FALSE while saving whatever value was in force before.  
     a. When this is done we should use `on.exit` to specify that it be reset when we're done. 
     b. this modification could be done whether or not the remove.unmatchables flag has been set. 
2.   We introduced `pairmatch`'s  remove.unmatchables option with a default value of `FALSE`, on the principle of minimizing surprises to existing users of the package.  Maybe it's time to change the default to `TRUE`: I can't think of situations in which the user would want `FALSE`.  The moment we introduce the feature described in this issue would be a good time for that change. 
An additional

**Comment by benthestatistician** [comment]
Notes: It looks as though `fullmatch` without infeasibility recovery is set up to handle negative omit.fractions, or almost set up for it. It doesn't look like the version with infeasibility recovery is arranged to be able to handle this, however.

**Comment by benthestatistician** [comment]
To do (if/when chance arises): 

- [ ] Review version of fullmatch w/o infeasibility recovery re continued support for negative omit.fractions
- [ ] fullmatch example tapping this functionality
- [ ] in `pairmatch.matrix`, touch up invocation of "fullmatch_try_recovery" option using `on.exit()`, as noted above
- [ ] new pairmatch functionality
- [ ] test(s)
- [ ] Default value of `pairmatch`'s `remove.unmatchables` option --> `TRUE`
- [ ] Check tests for changes.

**Comment by benthestatistician** [comment]
#132 is indirectly relevant.  Work toward it might make this easier.

**Comment by benthestatistician** [comment]
This works now in the issue132 branch, as of [issue132 84b86c4].

Additional remaining to-dos: 

- [ ] How does this approach respond to pairmatch problems with `controls`>1? Try a test case or two, add a little to test.pairmatch.R (which is skimpy on this front)
- [ ] Is use of `fullmatch_try_recovery` actually idle in this context? Think this through. 

(These may well be small matters, I just ran out of gas.)

**Comment by benthestatistician** [comment]
Answer to question about what this does w/ pairmatch problems w/ `controls`>1: at present, an error is thrown in these cases (i.e. cases where there aren't `controls` * (the number of treatments) members of the control group).  That's due to this error-checking in `fullmatch.matrix`, the necessity of which I didn't stop to think through:

```{r}
  if (any(omit.fraction < 0 & min.controls >= 2, na.rm=TRUE)) {
      stop("negative \'omit.fraction\' with \'min.controls\' >= 2 not permitted")
  }
```

Reifying this as an expectation, somewhat arbitrarily, in [issue132 8c81ab2].
