### ISSUE TITLE
NAs not allowed in treatment indicator

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#123]
I thought this was an issue we'd discussed before but I don't see anything in the queue.

Is there a reason for disallowing NAs in the treatment vector?

```
> data(nuclearplants)
> nuclearplants$pr[1] <- NA
> fullmatch(pr ~ cost, data = nuclearplants)
 Error in toZ(mf[, 1]) : NAs not allowed in treatment indicator. 
```

It seems to me that more natural behavior would be to return a match object which reports the NA treatment members as unmatchable.

This comes up because I had a client trying to do matching in Stata. I convinced her to pop the data over to R real quick and match, but because she had a reservoir of auxiliary control members with NA's in the treatment vector, it ended up being a bit more complicated because we had to truncate the data before matching and then merge it back.

**Comment by markmfredrickson** [comment]
Having the match be NA seems like a very reasonable action. We'd
effectively be doing what you did, just under the hood.

**Comment by benthestatistician** [comment]
I agree.  But let me think about it overnight; maybe something else will come to mind.  I recall thinking about this before.  I think I may have come to a similar conclusion but not gotten around to acting on it.  If I don't chime in here again by tomorrow, then that silence implies consent.

**Comment by benthestatistician** [comment]
Follow-up to previous comment: no reasons for hold back having occurred to me, I'm in favor of implementing the change @josherrickson proposes, to weed out observations with NAs in the treatment vector.

**Comment by benthestatistician** [comment]
@josherrickson if you're willing to implement this, please do! If not, or if not now, please don't hesitate to unassign yourself and reassign to me.

**Comment by josherrickson** [comment]
Sure, I can work on this. Seems to me this could be done in conjunction with the last comments in #124, enforcing treatment as binary (+ `NA`). To avoid re-opening that issue, @benthestatistician , do you want to proceed with that route? Either strictly (error if something besides 0/1 or logical or "0"/"1") or with an informative warning ("Assuming __ is the level of the control group, redefine treatment as dummy to ensure correct usage.")?

**Comment by benthestatistician** [comment]
As you'll see from my comments on the #124 thread, I think we'd serve our users a bit better by permitting non-binary numerics, provided that they unambiguously identify a treatment and a control.   I think there can be strict errors when this condition isn't met.

**Comment by benthestatistician** [comment]
Josh writes via email:

> I've almost got this work done in branch "toZwork". Turns out this is much easier than anticipated as `makeOptmatch` appears to correctly handle the dropped data so modifications are only needed in match_on.

> I haven't gotten to `match_on.function` yet but I suspect it will be just as straightforward (just dropping the NA's from `z`).

> I'd appreciate you throwing some tests at it, see if anything comes up.

**Comment by josherrickson** [comment]
I've finalized implementing this on the "toZwork" branch. All `match_on`, `fullmatch`, `pairmatch` and `exactMatch` versions support NA's in the treatment vector. Distance matrices will have smaller dimensions; optmatch objects will either have NA's for corresponding units (if `data` is specified) or be shorter (if `data` isn't specified for some cases).

Unless I hear otherwise (e.g. a failing example), I will merge into master later today.

**Comment by benthestatistician** [comment]
I've been getting good use out of these updates in my own work.  Don't hesitate push up to master if you haven't already, @josherrickson .

**Comment by josherrickson** [comment]
Sorry, slipped my mind. Merged into master. Closing.
