### ISSUE TITLE
Remove "omitted units" warning?

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#138]
What do we think about removing the warning out dropping unmatchable units: "The problem is infeasible with the given constraints; some units were omitted to allow a match."

I've received a few support emails where I think this warning confused more than enlightened users. We could also hide it behind an option for more verbose warnings.

**Comment by benthestatistician** [comment]
I'd be OK with an adjustment along these lines.  

A less extreme adaptation might be to warn about one or more **subproblems** being infeasible, rather than describing the entire problem that way. But maybe that's programming time and effort that we don't have to spend.
