### ISSUE TITLE
`makedist(z,x,f,within)` should ignore extraneous `within` entries 

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#142]
A computed ISM may be used to whittle down the sample size: for instance, fit propensity score model; calculate ISM based on it and possibly other constraints;  get rid of observations that would be excluded by the combination of constraints, then re-fit the PS model before matching.  In this workflow the intermediate ISM may have row or column entries that don't appear in the data frame used for re-fitting the PS.  Ideally we'd handle all of this without complaint, but instead I see

```{r}
> aglm = glm(formula = pr ~ . - cost, family = binomial, data = nuclearplants)
> mo1 <- caliper(aglm, width=1, data=nuclearplants)
> nuke.nopt <- subset(nuclearplants, pt==0)
> bglm <- update(aglm, data=nuke.nopt)
> mo3 <- match_on(bglm, within=mo1, data=nuke.nopt)
Error in makedist(z, x, f, within) : 
  Row and column names of within must match those of the data.
```

**Comment by benthestatistician** [comment]
Just noting that @adamrauh has a fix for this queued up in the issue147 branch of his fork, [commit no. 074cc06](https://github.com/adamrauh/optmatch/commit/074cc0644a7d924f44b02aafb69d824cb0386fdc?w=1).  A pull-in of that change including his replacement of
```r
if (!all(within@rownames %in% rns) | !(all(rns %in% within@rownames)) |
   !all(within@colnames %in% cns) | !(all(cns %in% within@colnames))) {
```
with 
```r
 if (!(all(rns %in% within@rownames)) | !(all(cns %in% within@colnames))) {
```
in `makedist.R` should close out this issue in the process.

**Comment by markmfredrickson** [comment]
I can confirm this is fixed in the pull (now in master). Closing.
