### ISSUE TITLE
biglm and R-release on Linux

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#152]
Noticed that we're seeing an error on [CRAN](https://cran.r-project.org/web/checks/check_results_optmatch.html) related to biglm, only on R release on Linux:

       no applicable method for 'bigglm' applied to an object of class "data.frame"

I don't think this is our fault, given that biglm exhibits the same error: https://cran.r-project.org/web/checks/check_results_biglm.html

No Action on our part, just noting in case it comes up in the future.

**Comment by markmfredrickson** [comment]
Thanks for flagging the upstream issue. CRAN has put us on notice that optmatch will be remove on 7/2 if this isn't fixed. I've email them to point out the upstream nature and the fact that is intermittent (i.e., I can't recreate on my linux install). I'll update this issue if we get a response.

**Comment by benthestatistician** [comment]
>
>
> I would suggest we move all of the biglm related testing material into a
file that we no longer include in the tarballs we submit to CRAN. Similar
to what we've recently decided to try out for RItools; see discussion of
recent pull requests on that repo, and associated references to that
comprise.

**Comment by josherrickson** [comment]
The tidyverse package 'broom' is being hit by this too (https://cran.r-project.org/web/checks/check_results_broom.html). I don't see any indication in their repo they're aware of or have addressed it yet, but we can hopefully take a hint from them when they do correct it.

**Comment by josherrickson** [comment]
@markmfredrickson Any update from CRAN? Do we need to push out a release removing these test before Monday?

**Comment by markmfredrickson** [comment]
We're ok for biglm. They want a fix for the `MASS::` issues in #151. I'll get a release pushed with the fix for #151.

**Comment by benthestatistician** [comment]
@josherrickson conveyed via email:

> Just wanted to point out that the biglm bug has vanished https://cran.r-project.org/web/checks/check_results_optmatch.html, though without an apparent update to biglm.

I think that means we're good on this issue.  Closing.
