### ISSUE TITLE
Test/Update for devtools 2.0

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#156]
`devtools` released version 2.0, which is a massive overhaul of their systems (https://cran.r-project.org/web/packages/devtools/news/news.html). 

Devtools is completely busted on my machine right now, but at some point we'll want to double-check that no modifications need to be made to continue support for devtools.

**Comment by josherrickson** [comment]
Just in case it helps anyone else, the error I'm seeing is

```
> devtools:::test()
Loading optmatch
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
  System command error
Calls: <Anonymous> ... with.default -> eval -> eval -> with_envvar -> force -> run
Execution halted
make: *** [.devtools] Error 1
```

**Comment by josherrickson** [comment]
I managed to get my devtools working and it looks like everything works now. @markmfredrickson would love a second opinion just to make sure I'm not missing something.

**Comment by markmfredrickson** [comment]
I've tried with both successfully:

    Package: devtools
    Title: Tools to Make Developing R Packages Easier
    Version: 1.13.6
    
    Package: devtools
    Title: Tools to Make Developing R Packages Easier
    Version: 2.0.1

**Comment by josherrickson** [comment]
Thanks @markmfredrickson.
