### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#157]
Re-ran the latest commit in Travis (https://travis-ci.org/markmfredrickson/optmatch/jobs/403517872) and we're failing with some message about API limits:

```
Installing R packages from GitHub: jimhester/covr
1.22s$ Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'
Error: HTTP error 403.
  API rate limit exceeded for 35.192.187.174. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  Rate limit remaining: 0/60
  Rate limit reset at: 2018-10-23 18:00:40 UTC
  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Add `GITHUB_PAT` to your travis settings as an encrypted variable.
Execution halted
```

Not sure if this is an issue on our end or on Travis' end. Quick search turned up this issue: https://github.com/git-lfs/git-lfs/issues/2133

**Comment by benthestatistician** [comment]
I suppose the next step is to try out the suggestion in the error message
(and the git-lfs issue 2133 discussion), to set up a Personal Access Token
and communicate it via travis settings.

**Comment by mhines-usgs** [comment]
I have a GITHUB_PAT token affiliated with my travis build and I still am intermittently getting this... it seems to be specific to using devtools::install_github ?

https://travis-ci.org/USGS-R/repgen/builds/446760948?utm_source=github_status&utm_medium=notification

**Comment by josherrickson** [comment]
Thanks for the hint @mhines-usgs . Looks like this is related to `install_github`: https://github.com/r-lib/remotes/issues/210, specifically https://github.com/r-lib/remotes/issues/210#issuecomment-432261541.

**Comment by josherrickson** [comment]
I tried adding the key to another package I maintain, and still get the API limit error. I still think this is an issue that Travis/Devtools need to work out, not us.

**Comment by mhines-usgs** [comment]
@josherrickson  -- you're correct, it seems like it's an issue with remotes, and they are supposed to be doing a release of it sometime 🤞 https://github.com/r-lib/devtools/issues/1906

**Comment by josherrickson** [comment]
There was a release of remotes the other day, and now Travis is passing (without us having to add a key). Going to close this now, but we'll want to keep an eye in case the issue re-appears.
