### ISSUE TITLE
Support `labelled` class treatment vectors

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#159]
Tibble objects can contain "labelled" vectors which are created during imports from Stata and SPSS.  We fail to support this.

```
> data <- haven::read_stata('tmp.dta')
> data$match <- fullmatch(foreign ~ mpg, data = data, min = 1, max = 2)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘toZ’ for signature ‘"labelled"’
```

We stopped supporting factor-type treatment vectors, but I'm not sure whether labelled objects are closer to factors or numerics. Once we decide that, we should either add an informative warning a la factors, or implement a `toZ` function for labelled.

**Comment by josherrickson** [comment]
Stata doesn't have a logical. All it has (basically) are numeric and string, but the numerics can have labels attached to them (they're still numerics, but you can think of them as factors to certain extent).

So this arises not because we're importing something non-logical, but because Stata has a label attached to an otherwise completely normal numeric variable.

I believe the `labelled` type has the same concept - its a number with a label, as opposed to a `factor` (I guess the main difference I'm noting here is that in a `factor,` the "number" can be meaningless. In a `labelled`, the number if quite meaningful.)

I think the best approach is just let `toZ.labelled` cast the input to numeric and let `toZ.numeric` handle checking the input. I can add something in the documentation about it.

**Comment by benthestatistician** [comment]
I'd be happy to go with Josh's solution of casting labelled numerics as
numeric.

**Comment by josherrickson** [comment]
This has been implemented (hoping not tempting fate by closing this issue before Travis finishes its final run and the branch gets merged in....)
