### ISSUE TITLE
rbind method for (BISM, BISM) should return a BISM

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#169]
At least, if the two BlockedInfinitySparseMatrix objects have blocks/subproblems of the same name.  Presently it seems to return a dense matrix instead.
Example:
```r
Z  <- rep(0:1, 3)
> Z
[1] 0 1 0 1 0 1
> B  <- rep(0:1, each=3)
> S  <- 1:6
> T  <- 5:0
> bismA  <- exactMatch(Z ~B) 
> bismA  <- match_on(Z~S, within=bismA)
> bismB  <- exactMatch(Z ~B)
> bismB  <- match_on(Z~T, within =bismB)
> is(bismA)
[1] "BlockedInfinitySparseMatrix" "InfinitySparseMatrix"       
[3] "vector"                     
> is(bismB)
[1] "BlockedInfinitySparseMatrix" "InfinitySparseMatrix"       
[3] "vector"                     
> rbind(bismA, bismB)
     [,1] [,2] [,3] [,4]
[1,]  0.5  0.5  0.5  0.5
[2,]  0.5  0.5  0.5  0.5
> is(rbind(bismA, bismB))
[1] "matrix"    "array"     "mMatrix"   "structure" "vector"   
```

**Comment by benthestatistician** [comment]
In the example above, `rbind()` seems to invoke `rbind.BlockedInfinitySparseMatrix` but not `rbind.InfinitySparseMatrix`, despite the former being defined as 
```r
rbind.BlockedInfinitySparseMatrix <- function(x, y, ...) {
  # demote the blocked representation to a regular ISM and call the usual cbind method
  rbind(as.InfinitySparseMatrix(x), y, ...)
```
@markmfredrickson , this was your work, if not exactly yesterday (33df452).  Could you check out what I've done in 7d14583 and (a) see if you can spot shortcomings & (b) suggest tests?

**Comment by markmfredrickson** [comment]
I'm happy with the change. Certainly seems like the easiest and most direct way. I've added two more tests to check that the rownames are all in their after rbinding.
