### ISSUE TITLE
failure on CRAN and R-devel

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#179]
https://cran.r-project.org/web/checks/check_results_optmatch.html

```
      > test_check("optmatch")
     -- 1. Failure: Math ops with vectors (@test.InfinitySparseMatrix.R#180) -------
     all(as.matrix(v%%A) == v%%m, na.rm = TRUE) isn't true.
    
     -- 2. Failure: Math ops with vectors (@test.InfinitySparseMatrix.R#180) -------
     all(as.matrix(v%/%A) == v%/%m, na.rm = TRUE) isn't true.
    
     == testthat results ===========================================================
     [ OK: 1498 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 2 ]
     1. Failure: Math ops with vectors (@test.InfinitySparseMatrix.R#180)
     2. Failure: Math ops with vectors (@test.InfinitySparseMatrix.R#180) 
```

I haven't looked into this any further, just flagging it here for now. I've restarted a Travis build with the latest commit on devel (https://travis-ci.org/markmfredrickson/optmatch/jobs/581862283), so we'll see what that says.

**Comment by josherrickson** [comment]
I tracked down what's going on, but haven't dove into exactly why this is occurring (primarily because I've been getting a segfault on any `.Call` call).

3.6:
```
> v%%m
       control
treated          1         2         4        6          9        10        11
      3 0.06382779 0.1086231 0.9355304      NaN        NaN       NaN       NaN
      5        NaN       NaN       NaN 1.877828        NaN       NaN       NaN
      7        NaN       NaN       NaN      NaN 0.15520101 0.3107194 2.0000000
      8        NaN       NaN       NaN      NaN 0.07805507 0.3508208 0.2292162
Warning message:
In v%%m : longer object length is not a multiple of shorter object length
> m%%v
       control
treated         1         2       4        6          9       10        11
      3 0.9361722 0.6114221 1.02149      NaN        NaN      NaN       NaN
      5       NaN       NaN     NaN 2.122172        NaN      NaN       NaN
      7       NaN       NaN     NaN      NaN 0.96119975 2.689281 0.2500829
      8       NaN       NaN     NaN      NaN 0.09650872 1.824590 1.3853919
Warning message:
In m%%v : longer object length is not a multiple of shorter object length
```

3.7 (devel):
```
v%%m
       control
treated          1         2         4        6          9        10        11
      3 0.06382779 0.1086231 0.9355304 3.000000 2.00000000 1.0000000 5.0000000
      5 2.00000000 1.0000000 5.0000000 1.877828 3.00000000 2.0000000 1.0000000
      7 3.00000000 2.0000000 1.0000000 5.000000 0.15520101 0.3107194 2.0000000
      8 4.00000000 3.0000000 2.0000000 1.000000 0.07805507 0.3508208 0.2292162
Warning message:
In v%%m : longer object length is not a multiple of shorter object length
> m%%v
       control
treated         1         2       4        6          9       10        11
      3 0.9361722 0.6114221 1.02149      NaN        NaN      NaN       NaN
      5       NaN       NaN     NaN 2.122172        NaN      NaN       NaN
      7       NaN       NaN     NaN      NaN 0.96119975 2.689281 0.2500829
      8       NaN       NaN     NaN      NaN 0.09650872 1.824590 1.3853919
Warning message:
In m%%v : longer object length is not a multiple of shorter object length
```

**Comment by josherrickson** [comment]
3.6:
```
> 3%%Inf
[1] NaN
```

3.7 (devel):
```
> 3%%Inf
[1] 3
```

Per this change in the [development notes](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html)
> x %% L for finite x no longer returns NaN when L is infinite, nor suffers from cancellation for large finite L, thanks to Long Qu's PR#17611.

**Comment by benthestatistician** [comment]
Thanks much for tracking this down, @josherrickson !  

In my view we could do without a test of `%%`, i.e. x mod y. Unless you or @markmfredrickson  says otherwise.

**Comment by josherrickson** [comment]
I would think that unless the current functionality of `vector%%ISM` (and similar) is desired for some reason, we would want to have it behave as standard R dictates. So that would suggest we update the code and get those tests to pass.

**Comment by benthestatistician** [comment]
Updating to get the tests to pass on R devel works for me. I was suggesting
another route in case it's a pain to deal with the differences between
devel and versions currently in circulation.

**Comment by josherrickson** [comment]
We discussed this offline and decided on Ben's original suggestion to modify the test. Summarizing the issue more directly here:

This is an order-of-operations issue. The test was comparing `matrix(scalar %% BISM)` versus `scalar %% matrix(BISM)`. In R 3.6 and prior these return the same results. In 3.7, due to the above referenced change, they return different results. Notably, in `matrix(scalar %% BISM)`, the mod is never calculated for the off-diagonal blocks so we properly end up with Inf's when converting to a matrix. In `scalar %% matrix(BISM)`, since we first cast to matrix, when we take the mod we are computing `scalar%%Inf` which results in a scalar rather than Inf.

(Similar results for integer division, `%/%`.)
