### ISSUE TITLE
CRAN "noSuggests"

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#184]
So it looks like CRAN is running an additional test where they are passing the `_R_CHECK_FORCE_SUGGESTS_=FALSE` argument to ignore Suggests in DESCRIPTION. We put most of the packages used exclusively for testing or vignettes (e.g. rmarkdown) in Suggests so we're getting some failures here.

https://cran.r-project.org/web/checks/check_results_optmatch.html
https://www.stats.ox.ac.uk/pub/bdr/noSuggests/optmatch.out

I'm not sure whether this requires any action on our part yet - we're not failing any primary checks, only some oddball new secondary check. I can't find much information about this change, so this issue is mostly to remind us to keep an eye out.

**Comment by josherrickson** [comment]
Well, the link on the main results page has vanished, but the noSuggests/optmatch.out file still exists.

**Comment by benthestatistician** [comment]
Maybe we dodged a bullet on this one, instead of making us try to fix they
fixed the request for a fix?

(At the moment we do fine on the cran check that Josh links to in the issue
statement, it's just the additional Oxford Ripley check that we fail. And
who among us expects to pass a supplemental check by Ripley?)

>

**Comment by josherrickson** [comment]
Either they changed their minds, or accidentally previewed a new feature. The reference has not re-appeared on the results page. I'll close this for now, though when the now-overdue latest issue of R Journal comes out, we should check Updates to CRAN to see if it is mentioned.
