### ISSUE TITLE
R 4.0.0 changes potentially affecting optmatch

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#186]
As I'm reading through the R-devel patch notes for 4.0.0, just joting down some notes which may affect us. Note that we pass all R-devel tests right now so none of these require us to do anything immediately.

- [x] matrix objects now also inherit from class "array", namely, e.g., class(diag(1)) is c("matrix", "array") which invalidates code assuming that length(class(obj)) == 1, an incorrect assumption that is less frequently fulfilled now. 
- [x] R now uses a stringsAsFactors = FALSE default, and hence by default no longer converts strings to factors in calls to data.frame() and read.table().
- [x]  New function .S3method() to register S3 methods in R scripts.
- [x] stopifnot() now allows customizing error messages via argument names, thanks to a patch proposal by Neal Fultz in PR#17688.

**Comment by benthestatistician** [comment]
:+1:

**Comment by josherrickson** [comment]
Re: stringsAsFactors. I looked through all places where we create data.frames and don't see anyplace we assume `stringsAsFactors = TRUE`, so checking it off.

**Comment by josherrickson** [comment]
Re: .S3method. Looking into this further, this is only for scripts; they recommend continuing to use NAMESPACE (via Roxygen) in packages. Checking it off.

**Comment by josherrickson** [comment]
RE: stopifnot. There's a few places (see below) where we use stopifnot, but they tend to be lower level issues that I suspect most users won't see. I don't know if we want to require 4.0.0 yet, so perhaps this change is a No Action. At best, it simplifies code from `if (...) stop("...")` to `stopifnot(..., "...")` and doesn't really improve things that much. 

Perhaps something to keep in mind if we ever do a large re-write of something and want to make the code more readable. 

```
><> git grep stopifnot                                               
R/feasible.R: stopifnot(is.numeric(size), length(size)==1,
R/match_on.R:  stopifnot(all(c('y','data') %in% names(x)))
R/matched.distances.R:  stopifnot(inherits(matchobj,"optmatch"))
R/mdist.R:    stopifnot(inherits(fmla, "formula"), inherits(structure.fmla, "formula"),
R/mdist.R:stopifnot(all(c('y', 'linear.predictors','data')%in%names(glmobject)))
R/mdist.R:## stopifnot(all.equal(dimnames(icv)[[1]],dimnames(dfr)[[2]]))
R/mdist.R:   stopifnot(!is.null(dimnames(inv.cov)[[1]]),
R/scores.R:    stopifnot(type %in% c("link", "response") )
R/stratumStructure.R:  stopifnot(is.numeric(min.controls), is.numeric(max.controls))
R/stratumStructure.R:  stopifnot(length(dim(x))==2, ncol(x)==1 || ncol(x)==2,
tests/exporting-methods.R:stopifnot(dim(tmp.m) == c(10,22))
tests/exporting-methods.R:stopifnot(class(tmp.m)[1] == "matrix")
tests/exporting-methods.R:stopifnot(dim(tmp.m) == c(10,22))
tests/exporting-methods.R:stopifnot(class(tmp.m)[1] == "matrix")
```
