### ISSUE TITLE
`match_on.numeric` to maintain dimension

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#189]
Example of problem: 
```r
 ( dat  <- data.frame(z=c(0,0,1), x=0:2, w=c(NA_real_, 1,2)) )
##   z x  w
## 1 0 0 NA
## 2 0 1  1
## 3 1 2  2
( within0  <- match_on(setNames(dat$w, nm=rownames(dat)),caliper=1, z=dat$z, data=dat) )
## within0
##       control
##treated 2
##      3 1
```
But observations with `NA` for `x` should be retained, as done by e.g. `match_on.formula()`:

```r
match_on(z~w, method="euclidean", caliper=1, data=dat)
##       control
## treated 2   1
##      3 1 Inf
```

This becomes a problem when trying to use the value of a `match_on.numeric()` call as `within=` argument to another `match_on()` call: 

```r
match_on(setNames(dat$x, nm=rownames(dat)), z=dat$z, data=dat, within=within0)
## Error in makedist(z, x, f, within) : 
##   Row and column names of within must match those of the data.
match_on(setNames(dat$x, nm=rownames(dat)), caliper=1, z=dat$z, data=dat, within=within0)
## Error in ismOpHandler("+", e1, e2) : non-conformable matrices
 match_on(z~x, data=dat, within=within0)
##Error in makedist(z, data, compute_mahalanobis, within) : 
##  Row and column names of within must match those of the data.
```

**Comment by josherrickson** [comment]
Adding names to `z` fixes this:

```
> ( dat  <- data.frame(z=c(0,0,1), x=0:2, w=c(NA_real_, 1,2)) )
  z x  w
1 0 0 NA
2 0 1  1
3 1 2  2
> ( within0  <- match_on(setNames(dat$w, nm=rownames(dat)),caliper=1, z=dat$z, data=dat) )
       control
treated 2
      3 1
> ( within0  <- match_on(setNames(dat$w, nm=rownames(dat)),caliper=1,
+                        z=setNames(dat$z, nm=rownames(dat)), data=dat) )
       control
treated 2   1
      3 1 Inf
```

The current documentation only requires names for `x`.

Options I see:
1) require names for `z`
2) copy over names from `x` if missing,
3) fix this to work without names for `z`

(I'd say there's an 80% chance that easiest fix is 2. anyways.)

**Comment by benthestatistician** [comment]
I agree about option 2, copy names over from `x` to `z`, being the most promising. In fact I see that that's already being done under the contingency that the user has supplied an `exclude` argument, as of 9fbfe5d .  So it would just be a matter of doing more generally what's already done in a special case.

**Comment by josherrickson** [comment]
One additional wrinkle - if `z` is named but differently from `x`, how do you want to handle it? I was thinking:

- If they contain the same names, regardless of order, re-order as appropriate and continue.
- If they contain different names, error.

Note that we already force `length(x) == length(z)`.

**Comment by josherrickson** [comment]
I ended up just using the guidelines above since I was working on it; let me know if you think anything should change.

**Comment by benthestatistician** [comment]
Those rules make sense to me.

>
