### ISSUE TITLE
Integer overflow in checking problem size

### ISSUE THREAD

**Issue by ngreifer** [markmfredrickson/optmatch#209]
See the problem described [here](https://stackoverflow.com/questions/68806729/matchit-propensity-score-matching-package-for-r-throws-errors-concerning-nas-p).

When checking to see if the problem size is too big, `optmatch` multiplies two integers to compute `nc * nr`. If `nc` and `nr` are large, the resulting value cannot be stored as an integer and overflows, yielding `NA` and a warning. In `optmatch`, the `NA` yields a hard to interpret error. Perhaps `as.numeric(nc) * as.numeric(nr)` should be used instead.

**Comment by benthestatistician** [comment]
Thanks much for the bug report, @ngreifer .   4d0e0a3 should fix it, and will likely head to CRAN over the course of next week.  In the meantime it can be had with `devtools::install_github()`.

**Comment by acnash** [comment]
I've installed the 4d0e0a3 branch, and although I'm no longer seeing an error concerning `nc * nr` as described above, I'm now getting the following instead:

```
Error in cbind(treatmentids, controlids) : 
  long vectors not supported yet: ../include/Rinlinedfuns.h:535
```

**Comment by benthestatistician** [comment]
Thanks for the report, Anthony.  Sorry this didn't fix your problem.
Unfortunately I suspect that none of us active optmatch developers are in a
position to troubleshoot this issue further. In that case I'm afraid we
can't handle a problem of your size at present.

From the man page about [Long Vectors](
https://stat.ethz.ch/R-manual/R-devel/library/base/html/LongVectors.html),
it looks like the Fortran interface wouldn't be able to grapple with them
even if we were to fix this specific problem.

>
