### ISSUE TITLE
Un-graceful failure when only 2 units are involved

### ISSUE THREAD

**Issue by ngreifer** [markmfredrickson/optmatch#211]
I know this may seem like a strange issue but it was brought up to me by a user of `MatchIt`. When there is only one treated and one control unit (i.e., so the distance matrix is 1x1), an error is thrown when running `fullmatch()`. See below:

``` r
d <- matrix(.5, dimnames = list("a", "b"))
optmatch::fullmatch(d)
#> Warning in optmatch::fullmatch(d): Without 'data' argument the order of the match is not guaranteed
#>     to be the same as your original data.
#> Error in if (maxerr > tolerance) {: missing value where TRUE/FALSE needed
```

The missing value is a `NaN` in `SubDivStrat()` but is caused by the following line in `fullmatch.matrix()`:

https://github.com/markmfredrickson/optmatch/blob/94d2669582bcc5ddf580bc084665af4811a57379/R/fullmatch.R#L466

Because `total.n == 2`, the denominator is zero and `tol.frac` is `Nan`. `tol.frac` is multiplied by `TOL` on line 487 and passed to `tolerance` in `SubDivStrat()` as `NaN`, yielding the error. A solution might be to handle this unusual corner case by automatically assigning the units to the same stratum unless the distance value was `Inf`, or by using a different formula for `tol.frac` that doesn't yield this issue. Or if you don't think this is worthy of a fix, I can just do that myself in `MatchIt`.

This kind of thing can happen when a user is looping through strata of units to match and unknowingly ends up with a stratum containing one treated and one control unit. Of course we'd prefer for users not to use `fullmatch()` to match a single unit to another, but this can happen with automation, which is why it occurred in `MatchIt`.

**Comment by markmfredrickson** [comment]
Thanks for bringing this to our attention and detailed diagnosis. I think the suggestion to automatically match if there are only two units makes the most sense. We'll get this implemented and push out a fix.
