### ISSUE TITLE
Error in if ((nc * nr > getMaxProblemSize()) && warning.requested) {: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by SulevR** [markmfredrickson/optmatch#213]
A friend of mine used optmatch ver 09-15 and got an error:

`Error in if ((nc * nr > getMaxProblemSize()) && warning.requested) {: missing value where TRUE/FALSE needed`

It is really hard to understand what could be the problem as I do not have access to the underlying data. Could it be somehow connected to #209 and therefore an upgrade to version 09-16 is suggested?

**Comment by SulevR** [comment]
Can you update the official version in CRAN repositories also? Seems that version 09-16 resolves this issue, but it is version 09-15 which is still in CRAN.

**Comment by josherrickson** [comment]
We're in the process of packing up a new version; it should be up in the next few weeks. In the meantime, you can follow the directions [here](https://github.com/markmfredrickson/optmatch#using-a-development-version-of-optmatch) to install the current development version.

**Comment by josherrickson** [comment]
Closing as we're now well past 09-16. @SulevR please comment if this has not been fully resolved.
