### ISSUE TITLE
Using precomputed distance matrix in fullmatch

### ISSUE THREAD

**Issue by jay-sf** [markmfredrickson/optmatch#214]
Hi Mark,

first of all thank you for maintaining the great `optmatch` package, which allows perhaps the most flexibility in applying further methods after matching from what I've seen so far.

I have an issue related to the `x` argument of `fullmatch` or `pairmatch` respectifvely. The documentation states that _"alternatively, a precomputed distance may be entered."_ I couldn't find an example or documerntation  of exactly how this is done.  I am therefore not entirely sure whether I have done it right.

Specifically I'd like to combine propensity score matching and pair-/fullmatching. For this I predict propensity scores from a `glm`, calculate a distance matrix `distmat`, and put it into `fullmatch` or `pairmatch` as in the following small example:

```
data("lalonde", package='Matching')
## ps model
lalonde$ps <- glm(treat ~ age + I(age^2) + educ + I(educ^2) + black +
                    hisp + married + nodegr + re74  + I(re74^2) + re75 +
                    I(re75^2) + u74 + u75, family=binomial(), data=lalonde)$fit

library(optmatch)
ps_tmp <- lalonde$ps |> setNames(rownames(lalonde))
distmat <- abs(outer(ps_tmp[lalonde$treat == 1], ps_tmp[lalonde$treat == 0], `-`))   ## distance matrix

## optimal pair matching ----
lalonde$opt_pair <- optmatch::pairmatch(distmat, data=lalonde)
summary(lm(re78 ~ treat + opt_pair, lalonde))$coe[2, ] |> round(3)
# Estimate Std. Error    t value   Pr(>|t|) 
# 1998.697    670.318      2.982      0.003 

## optimal full matching ----
lalonde$opt_full <- optmatch::fullmatch(distmat, data=lalonde)
summary(lm(re78 ~ treat + opt_full, lalonde))$coe[2, ] |> round(3)
# Estimate Std. Error    t value   Pr(>|t|) 
# 1833.733    684.019      2.681      0.008 
```
Please could you verify whether the distance matrix is calculated in the right way, as `optmatch` needs it?

Thanks!

Cheers

**Comment by benthestatistician** [comment]
Hi Jay-sf, What you're doing should work. You find examples of other recommended approaches (which may work much better with larger data sets) in the `fullmatch-vignette` vignette.

**Comment by jay-sf** [comment]
Hope you don't mind a small follow-up on this. In the `distmat` in the MWE above, rows are treated, columns are control. Is this correct or should it be transposed? If I use `distmat` and `t(distmat)` I get slightly different values. Thanks!

**Comment by josherrickson** [comment]
Correct; the distance matrix expects rows as treatment group and columns as control.

**Comment by jay-sf** [comment]
@josherrickson Great, thanks a ton!
