### ISSUE TITLE
Optmatch not on CRAN (was: Unable to install optmatch as RItools is no longer available)

### ISSUE THREAD

**Issue by riazgillani** [markmfredrickson/optmatch#215]
Hello - I am receiving the following error when I try to install the optmatch package: “dependency ‘RItools’ is not available”

I notice that RItools has been removed from the CRAN repository: https://cran.r-project.org/web/packages/RItools/index.html

Will RItools be made available again? Is there a workaround to enable the use of optmatch in the mean time?

Thanks,
Riaz

**Comment by RoseString** [comment]
This worked for me

```
library(devtools)
install_github("markmfredrickson/RItools")
install_github("markmfredrickson/optmatch") 
```

**Comment by josherrickson** [comment]
Thanks @RoseString.  Installing the developer version is indeed the best workaround. We've submitted updates for both packages and hope they'll be back in shortly. Sorry for the inconvenience.

**Comment by riazgillani** [comment]
Thank you both!

**Comment by lovebead22** [comment]
> This worked for me
> 
> ```
> library(devtools)
> install_github("markmfredrickson/RItools")
> install_github("markmfredrickson/optmatch") 
> ```

Tried this but getting error: make: gfortran: No such file or directory
make: *** [relax4s.o] Error 1
ERROR: compilation failed for package ‘optmatch’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/optmatch’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/g6/kdlzyn916lqbt424jym2_x3xwt9pgz/T//Rtmpyu1iWb/file2eb53072f5a7/optmatch_0.9-17.tar.gz’ had non-zero exit status

**Comment by LliliansCalvo** [comment]
Hi I am trying to install the developer version but I am receiving this error:

**Comment by josherrickson** [comment]
Hi @LliliansCalvo , you'll need to install gfortran to use the developer version. You can install it with a package manager (I know homebrew has it, I'd assume macports does as well but I'm not sure) or you can install it manually from e.g. https://cran.r-project.org/bin/macosx/tools/

However, the RItools package has been made re-available on CRAN so I hopefully that optmatch will reappear shortly as well, so you may be better of waiting for that.

**Comment by ngreifer** [comment]
Do you get the sense that `optmatch` will be back on CRAN in the next few days? We in the "packages depend on `optmatch`" community are getting a bit nervous because allowing a dependence on a package not on CRAN can be a real headache. I'm happy to help however I can to get `optmatch` back on CRAN.

Noah

**Comment by josherrickson** [comment]
We expected it to appear when its dependencies were restored (which happened last night). We've reached out to CRAN to clarify our next steps. Hopefully it can be restored by tomorrow.

**Comment by ngreifer** [comment]
Okay, great! Thanks! They may have you resubmit with an increased version number.

**Comment by josherrickson** [comment]
Yeah I'm kinda expecting that, but figured we'd double check to avoid passing them extra unnecessary work.

**Comment by ngreifer** [comment]
Sorry to bug, but any news on this?

**Comment by josherrickson** [comment]
We ended up submitting a version number bump'd version on Tuesday but haven't heard from that or the email to CRAN yet unfortunately.

**Comment by ngreifer** [comment]
Thank you!

**Comment by markmfredrickson** [comment]
I got word today that the CRAN team has decided not to host a package with a non-open source license (the R code in for optmatch is all open source, the RELAX Fortran code that solves the network flow problem is a "free for academic use" license). We are looking into our options, but optmatch is going to remain off CRAN for at least the present.

**Comment by markmfredrickson** [comment]
Changed the title in case anyone comes here looking for why optmatch is missing. 

As a temporary work around, you can use the Microsoft CRAN snapshots to install the most recent version of optmatch:

```
> install.packages("optmatch", repos = "https://cran.microsoft.com/snapshot/2022-02-15/")
```

**Comment by ngreifer** [comment]
This is unfortunate! Thank you for keeping us updated. Would you consider making a [`drat`](https://dirk.eddelbuettel.com/code/drat.html) repository for `optmatch` so CRAN packages that weakly depend on `optmatch` (like `MatchIt`) can still use its functionality?

**Comment by benthestatistician** [comment]
Thanks for raising the possibility of a `drat` repository, @ngreifer.  We're considering it.

**Comment by benthestatistician** [comment]
Can anyone point me to official CRAN policies about packages that are dependent on packages hosted elsewhere, potentially with non-FOSS licenses?   Failing that, CRAN policies about package dependencies on software external to R, potentially with non-FOSS licence? 

As I understand it, @ngreifer 's suggestion that we host optmatch in a drat repo would create such a dependency for MatchIt. Another  scenario we're considering is to factor enough out of optmatch for what remains of it to have a FOSS license, with a `drat` repo for the rest.

**Comment by markmfredrickson** [comment]
From the [CRAN policies page](https://cran.r-project.org/web/packages/policies.html):

> Packages on which a CRAN package depends should be available from a mainstream repository: if any mentioned in ‘Suggests’ or ‘Enhances’ fields are not from such a repository, where to obtain them at a repository should be specified in an ‘Additional_repositories’ field of the DESCRIPTION file (as a comma-separated list of repository URLs) or for other means of access, described in the ‘Description’ field.
> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms. (‘Writing R Extensions’ recommends that they are always used conditionally.)

This suggests that non-CRAN packages are explicitly allowed, perhaps with the use of `Additional_repositories` suitably populated.

**Comment by josherrickson** [comment]
We're back on CRAN. Sorry for the delay. This version has removed the code which was under the non-standard license. End users should see no difference but please let us know otherwise.
