### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gl-ybnbxb** [markmfredrickson/optmatch#221]
I keep getting errors (showed below) when installing the package. Could you help to fix this?
ERROR: compilation failed for package ‘optmatch’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/optmatch’
installation of package ‘/var/folders/lg/ypgl3x9n6m79t5xxm5h025b00000gn/T//RtmpcJwBfi/file906324ae0484/optmatch_0.9-17.tar.gz’ had non-zero exit status

**Comment by benthestatistician** [comment]
I'm afraid we won't be able to help you with compiler issues, but you might try installing the pre-compiled version: `install.packages("optmatch", type="mac.binary")`.

**Comment by markmfredrickson** [comment]
Additionally, did you explicitly ask for version 0.9-17? The current version, with binaries, is 0.10.3.
