### ISSUE TITLE
Error when using R in SPSS

### ISSUE THREAD

**Issue by CNwangbin** [markmfredrickson/optmatch#225]
The version of my R is 3.5, I try to install 'optmatch' package but also get this Error. It seems the package 'optmatch' version I installed not match my R version 3.5. Is there any way to find the match version of 'optmatch'?
`(...): package or namespace load failed for 'optmatch' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 object 'vI' not found`

**Comment by josherrickson** [comment]
Hi CNwangbin,

Looking around online, this seems to be related to a bug in the 3.x line (based on all results I can find being from around 5 years ago, when 3.5 was out). It's not an optmatch issue, rather something that went wrong with the install. 

The most obvious suggestion is to move to the R 4.X branch. 3.5 is incredibly old and unsupported by almost any packages these days. If that's not feasible, you could try removing optmatch and reinstalling it. 

Here are several discussions online about it where users are suggesting different incantations of the `install.packages` command which may be useful:

https://community.rstudio.com/t/not-able-to-load-tidyverse-object-vi-not-found/10243
https://stackoverflow.com/questions/35942473/error-in-loadnamespace-object-vi-not-found-with-package-plm
https://community.rstudio.com/t/object-vi-not-found/38243

**Comment by CNwangbin** [comment]
Thanks for your quick reply. I fixed this bug by same ways now.
