### ISSUE TITLE
R-devel warnings

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#233]
R 4.3.2 is coming out on Halloween. Against R-devel we see:

```r

* checking S3 generic/method consistency ... NOTE
Mismatches for apparent methods not registered:
update:
  function(object, ...)
update.NodeInfo:
  function(old, new, ...)

predict:
  function(object, ...)
predict.CBPS:
  function(x, newdata, type, ...)
See section 'Registering S3 methods' in the 'Writing R Extensions'
manual.
```

**Comment by josherrickson** [comment]
@benthestatistician For the `update.NodeInfo`, it looks like while `update.formula` takes `old` and `new` arguments, `stats::update` takes in only the `object` named argument and this is becoming a NOTE in the development version. 

It looks like `update.NodeInfo` isn't exported, nor can I see it being called from anywhere. Any objection to changing the first argument to `object` instead of `new` so it passes check? All tests & check pass with this modification.

**Comment by benthestatistician** [comment]
I have no objections, either to the proposed `update.NodeInfo()` modification or to the analogous modification to `predict.CBPS()`.   Thanks for a nice tidy solution, @josherrickson.
