### ISSUE TITLE
R CMD check produces C++ errors for R unstable r87029

### ISSUE THREAD

**Issue by nullsatz** [markmfredrickson/optmatch#237]
Two problems that must be fixed by 4 October:

1. First
`Compilation fails with _R_USE_STRICT_R_HEADERS_=true, which defines
STRICT_R_HEADERS to 1 which removes

- the legacy definition of PI (use POSIX's M_PI, available in R fer ever).
- the RS.h declarations for Calloc, Realloc, Free (use R_ forms i
  available since R 3.4.0).

The aim is to clean the namespace: in particular having a definition
for Free has conflicted with some packages' C++ code.`

2. And also
`In file included from distances.cc:4:
distances.h:1: warning: "R_NO_REMAP" redefined
    1 | #define R_NO_REMAP
      | 
<command-line>: note: this is the location of the previous definition
distances.cc: In function ‘SEXPREC* mahalanobisHelper(SEXP, SEXP, SEXP)’:
distances.cc:32:10: error: ‘nrows’ was not declared in this scope
   32 |     nv = nrows(index),
      |          ^~~~~
distances.cc:43:3: error: ‘GetMatrixDimnames’ was not declared in this scope; did you mean ‘Rf_GetMatrixDimnames’?
   43 |   GetMatrixDimnames(data, &row_names, &cl, &rn, &cn);
      |   ^~~~~~~~~~~~~~~~~
      |   Rf_GetMatrixDimnames
In file included from map.h:22,
                 from distances.cc:3:
distances.cc:48:20: error: ‘allocVector’ was not declared in this scope; did you mean ‘Rf_allocVector’?
   48 |   PROTECT(result = allocVector(REALSXP, nv));
      |                    ^~~~~~~~~~~
/home/bucknerj/apps/r/r-devel/lib64/R/include/Rinternals.h:385:36: note: in definition of macro ‘PROTECT’
  385 | #define PROTECT(s)      Rf_protect(s)
      |                                    ^
distances.cc:63:20: error: ‘n’ was not declared in this scope
   63 |     for(j = 0; j < n; j++) {
      |                    ^
distances.cc:67:41: error: ‘nr’ was not declared in this scope; did you mean ‘rn’?
   67 |         innerSum += (real_data[va + k * nr]
      |                                         ^~
      |                                         rn
distances.cc:71:45: error: ‘nr’ was not declared in this scope; did you mean ‘rn’?
   71 |       sum += innerSum * (real_data[va + j * nr] - real_data[vb + j * nr]);
      |                                             ^~
      |                            `

**Comment by nullsatz** [comment]
Our code uses oldschool SEXP objects directly. I believe if we modernized the Rcpp code along the lines of, for example, using Rcpp objects like `NumericMatrix`, `NumericVector`, and so on, these errors would disappear.

I have been able to build R unstable revision r87029 on a Rocky 9 box. The only advice I have is to make sure to install xorg-x11-fonts and a whole host of *-devel packages.

I have also been able to reproduce the 2nd error with this version of R.

**Comment by nullsatz** [comment]
added a new branch rcpp-fixes that fixes everything R-devel complains about

completely modernized distances.cc

unfortunately getting wrong results

work in progress

may roll back modernization and introduce some light weight fixes as in other cc files if I can't get the results correct in a day or two

**Comment by nullsatz** [comment]
I have fixed the problems with mahal distances.

I'm not seeing an error related to POSIX's M_PI. I've grepped for PI and can't find a reference in the code. If anyone knows where it is, let me know and I'll fix it.

I think this code is ready to go, but I would appreciate it if a second person did some testing before merging.

In summary, the changes are: distances.cc has been modernized, the rest of the Rcpp code has been lightly edited to remove the 'R CMD check' errors.

I think the rest of the code should be modernized but maybe that's not a high priority right now.

**Comment by benthestatistician** [comment]
I don't think we're getting dinged on anything having to do with pi.  Our `USE_STRICT_HEADERS= true` problems seem to have do do with the set of facilities that setting removes, having to do with `Calloc` and such.  [Here's](https://www.stats.ox.ac.uk/pub/bdr/Strict/optmatch.out) the relevant log from the CRAN test.

**Comment by benthestatistician** [comment]
On released R version 4.4.1, aarch64-apple-darwin23.2.0 platform, rcpp-fixes 7818b01, make check works for me as expected.  (If that's what you had in mind by "a second person doing some testing" also, @nullsatz.)

**Comment by nullsatz** [comment]
I also need to check that memory and time efficiency hasn't been compromised by moving away from the R internal api.

**Comment by nullsatz** [comment]
> I don't think we're getting dinged on anything having to do with pi. Our `USE_STRICT_HEADERS= true` problems seem to have do do with the set of facilities that setting removes, having to do with `Calloc` and such. [Here's](https://www.stats.ox.ac.uk/pub/bdr/Strict/optmatch.out) the relevant log from the CRAN test.

I fixed that.

**Comment by benthestatistician** [comment]
Good to hear.  To weigh in on something else you mentioned, @nullsatz: 
>  I think the rest of the code should be modernized but maybe that's not a high priority right now.

-- Probably not the highest priority, no; but I wouldn't call it low priority either.  I think I saw that R Core had decided to to move to C+17 as their standard.  If you see other ways in which we're out of step with that standard, it's likely that they'll enforce it for an upcoming R release.  It's nicer to stay ahead of these sorts of demands for fixes than to have to address them on their deadlines.

**Comment by benthestatistician** [comment]
The performance vignette (vignettes/performance/) may be helpful for checking changes in resource consumption.  In order to compile it you'll need to put this LaTeX style file into vignettes/ :  [Sweave.sty.gz](https://github.com/user-attachments/files/16967224/Sweave.sty.gz)

**Comment by benthestatistician** [comment]
PS: To run the R code in `performance.Rnw` and create `performance.tex`, from `/vignettes/performance/` one does

```
% R CMD Sweave performance.Rnw 
```
from the command line. With `Sweave.sty` in `/vignettes/`, of course.

**Comment by josherrickson** [comment]
I ran the current master branch and the rcpp-fixes against the [win-builder](https://win-builder.r-project.org/) with R-devel. Master fails to build:

```
map.cc: In function 'MAP* create_map(SEXP)':
map.cc:47:31: error: expected primary-expression before ')' token
   47 |   MAP * strpos = Calloc(1, MAP);
      |                               ^
map.cc:47:18: error: 'Calloc' was not declared in this scope; did you mean 'calloc'?
   47 |   MAP * strpos = Calloc(1, MAP);
      |                  ^~~~~~
      |                  calloc
map.cc:48:32: error: expected primary-expression before 'struct'
   48 |   strpos->hash_tab = Calloc(1, struct hsearch_data);
      |                                ^~~~~~
map.cc:52:41: error: expected primary-expression before ')' token
   52 |   strpos->entries = Calloc(n_strs, ENTRY);
      |                                         ^
map.cc: In function 'void delete_map(MAP*)':
map.cc:75:3: error: 'Free' was not declared in this scope; did you mean 'free'?
   75 |   Free(strpos->entries);
      |   ^~~~
      |   free
map.cc: In function 'int hcreate_r(size_t, hsearch_data*)':
map.cc:164:58: error: expected primary-expression before ')' token
  164 |   htab->table = (_ENTRY *) Calloc (htab->size + 1, _ENTRY);
      |                                                          ^
map.cc:164:28: error: 'Calloc' was not declared in this scope; did you mean 'calloc'?
  164 |   htab->table = (_ENTRY *) Calloc (htab->size + 1, _ENTRY);
      |                            ^~~~~~
      |                            calloc
map.cc: In function 'void hdestroy_r(hsearch_data*)':
map.cc:181:3: error: 'Free' was not declared in this scope; did you mean 'free'?
  181 |   Free(htab->table);
      |   ^~~~
      |   free
make: *** [D:/RCompile/recent/R/etc/x64/Makeconf:295: map.o] Error 1
```

But the rcpp-fixes branch builds without complaint. It does have the following notes in the install, no idea if they're important or not.

```
In file included from D:/RCompile/recent/R/include/R.h:73,
                 from subsetInfSparseMatrix.h:1,
                 from subsetInfSparseMatrix.cc:1:
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h: In function 'void Rcpp::Rf_warning(const char*, Args&& ...) [with Args = {const char*}]':
D:/RCompile/recent/R/include/R_ext/Error.h:100:17: warning: infinite recursion detected [-Winfinite-recursion]
  100 | #define warning Rf_warning
      |                 ^~~~~~~~~~
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h:46:13: note: in expansion of macro 'warning'
   46 | inline void warning(const char* fmt, Args&&... args ) {
      |             ^~~~~~~
In file included from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions.h:180,
                 from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/RcppCommon.h:130,
                 from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp.h:27,
                 from subsetInfSparseMatrix.cc:3:
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h:47:15: note: recursive call
   47 |     Rf_warning("%s", tfm::format(fmt, std::forward<Args>(args)... ).c_str());
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```


I don't know of another way to test against CRAN's advanced other than submitting, so I think we should work towards pushing a new version out shortly, in case we need to time for another round of fixes prior to the October deadline.

**Comment by nullsatz** [comment]
I can fix this early this week. I actually removed my homegrown MAP. I don’t know how it kept working for me. Sorry! 🤷 Best JoshOn Sep 15, 2024, at 9:43 AM, Josh Errickson ***@***.***> wrote:﻿
I ran the current master branch and the rcpp-fixes against the win-builder with R-devel. Master fails to build:
map.cc: In function 'MAP* create_map(SEXP)':
map.cc:47:31: error: expected primary-expression before ')' token
   47 |   MAP * strpos = Calloc(1, MAP);
      |                               ^
map.cc:47:18: error: 'Calloc' was not declared in this scope; did you mean 'calloc'?
   47 |   MAP * strpos = Calloc(1, MAP);
      |                  ^~~~~~
      |                  calloc
map.cc:48:32: error: expected primary-expression before 'struct'
   48 |   strpos->hash_tab = Calloc(1, struct hsearch_data);
      |                                ^~~~~~
map.cc:52:41: error: expected primary-expression before ')' token
   52 |   strpos->entries = Calloc(n_strs, ENTRY);
      |                                         ^
map.cc: In function 'void delete_map(MAP*)':
map.cc:75:3: error: 'Free' was not declared in this scope; did you mean 'free'?
   75 |   Free(strpos->entries);
      |   ^~~~
      |   free
map.cc: In function 'int hcreate_r(size_t, hsearch_data*)':
map.cc:164:58: error: expected primary-expression before ')' token
  164 |   htab->table = (_ENTRY *) Calloc (htab->size + 1, _ENTRY);
      |                                                          ^
map.cc:164:28: error: 'Calloc' was not declared in this scope; did you mean 'calloc'?
  164 |   htab->table = (_ENTRY *) Calloc (htab->size + 1, _ENTRY);
      |                            ^~~~~~
      |                            calloc
map.cc: In function 'void hdestroy_r(hsearch_data*)':
map.cc:181:3: error: 'Free' was not declared in this scope; did you mean 'free'?
  181 |   Free(htab->table);
      |   ^~~~
      |   free
make: *** [D:/RCompile/recent/R/etc/x64/Makeconf:295: map.o] Error 1

But the rcpp-fixes branch builds without complaint. It does have the following notes in the install, no idea if they're important or not.
In file included from D:/RCompile/recent/R/include/R.h:73,
                 from subsetInfSparseMatrix.h:1,
                 from subsetInfSparseMatrix.cc:1:
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h: In function 'void Rcpp::Rf_warning(const char*, Args&& ...) [with Args = {const char*}]':
D:/RCompile/recent/R/include/R_ext/Error.h:100:17: warning: infinite recursion detected [-Winfinite-recursion]
  100 | #define warning Rf_warning
      |                 ^~~~~~~~~~
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h:46:13: note: in expansion of macro 'warning'
   46 | inline void warning(const char* fmt, Args&&... args ) {
      |             ^~~~~~~
In file included from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions.h:180,
                 from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/RcppCommon.h:130,
                 from D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp.h:27,
                 from subsetInfSparseMatrix.cc:3:
D:/RCompile/CRANpkg/lib/4.5/Rcpp/include/Rcpp/exceptions/cpp11/exceptions.h:47:15: note: recursive call
   47 |     Rf_warning("%s", tfm::format(fmt, std::forward<Args>(args)... ).c_str());
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I don't know of another way to test against CRAN's advanced other than submitting, so I think we should work towards pushing a new version out shortly, in case we need to time for another round of fixes prior to the October deadline.

**Comment by benthestatistician** [comment]
Sounds great, @nullsatz .  As I may have mentioned (but just to be sure), there's an advantage in submitting to CRAN of not provoking notes or warnings of any kind.  Then you escape human review, which sometimes leads to special requirements that can be burdensome to address.

**Comment by josherrickson** [comment]
Just to make sure I was clear, the erroring on master don't concern me, I was just showing that win-builder with RDevel was catching the types of errors CRAN was telling us about. The lack of errors on your branch is terrific!

Ben's comment is a great point, but I will mention that those C issues did not create a warning/note from the CRAN check. I was just pasting them here in case it's useful. From a CRAN submission perspective, I think the branch is ready to go, as soon as Josh gives the go-ahead and merges it to master.

**Comment by nullsatz** [comment]
I re-read [the win-builder comment](https://github.com/markmfredrickson/optmatch/issues/237#issuecomment-2351600248) with more care.

I was able to remove the `R.h` include from `src/subsetInfSparseMatrix.cc`. The changes are passing `R CMD check`. I will upload this to the win-builder tonight and report back, but I believe the warning will be gone (for this file at least).

**Comment by nullsatz** [comment]
Win-builder output looks clean to me. I changed the maintainer so that I could intercept the email and make changes as needed. Since everything looks fine, I have changed the maintainer back to @josherrickson 

I think we can probably submit this week. Let me know what y'all want me to do.

00check.log
```* using log directory 'd:/RCompile/CRANguest/R-devel/optmatch.Rcheck'
* using R Under development (unstable) (2024-09-15 r87152 ucrt)
* using platform: x86_64-w64-mingw32
* R was compiled by
    gcc.exe (GCC) 13.2.0
    GNU Fortran (GCC) 13.2.0
* running under: Windows Server 2022 x64 (build 20348)
* using session charset: UTF-8
* checking for file 'optmatch/DESCRIPTION' ... OK
* this is package 'optmatch' version '0.10.7.9001'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [62s] NOTE
Maintainer: 'Josh Buckner <bucknerj@umich.edu>'

Version contains large components (0.10.7.9001)

New maintainer:
  Josh Buckner <bucknerj@umich.edu>
Old maintainer(s):
  Josh Errickson <jerrick@umich.edu>

Unknown, possibly misspelled, fields in DESCRIPTION:
  'Remotes'

Suggests or Enhances not in mainstream repositories:
  rrelaxiv
Availability using Additional_repositories specification:
  rrelaxiv   no   ?                             
  ?           ?   https://errickson.net/rrelaxiv
Additional repositories with no packages:
  https://errickson.net/rrelaxiv
* checking package namespace information ... OK
* checking package dependencies ... NOTE
Package suggested but not available for checking: 'rrelaxiv'
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'optmatch' can be installed ... OK
* used C compiler: 'gcc.exe (GCC) 13.2.0'
* used C++ compiler: 'g++.exe (GCC) 13.2.0'
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking whether startup messages can be suppressed ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... [15s] OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking LazyData ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
* checking compiled code ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ... [47s] OK
  Running 'exporting-methods.R'
  Running 'testthat.R' [46s]
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... [14s] OK
* checking HTML version of manual ... OK
* DONE
Status: 2 NOTEs```

00install.out
```* installing *source* package 'optmatch' ...
** using staged installation
** libs
using C compiler: 'gcc.exe (GCC) 13.2.0'
using C++ compiler: 'g++.exe (GCC) 13.2.0'
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c cuseful.cc -o cuseful.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c distances.cc -o distances.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c ism.cc -o ism.o
gcc  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -Wstrict-prototypes -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c optmatch_init.c -o optmatch_init.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c r_smahal.cc -o r_smahal.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c smahal.cc -o smahal.o
g++ -std=gnu++17  -I"D:/RCompile/recent/R/include" -DNDEBUG -DUSE_FC_LEN_T -I'D:/RCompile/CRANpkg/lib/4.5/Rcpp/include'   -I"d:/rtools44/x86_64-w64-mingw32.static.posix/include" -DSTRICT_R_HEADERS=1     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign   -c subsetInfSparseMatrix.cc -o subsetInfSparseMatrix.o
g++ -std=gnu++17 -shared -s -static-libgcc -o optmatch.dll tmp.def RcppExports.o cuseful.o distances.o ism.o optmatch_init.o r_smahal.o smahal.o subsetInfSparseMatrix.o -LD:/RCompile/recent/R/bin/x64 -lRlapack -LD:/RCompile/recent/R/bin/x64 -lRblas -lgfortran -lm -lquadmath -Ld:/rtools44/x86_64-w64-mingw32.static.posix/lib/x64 -Ld:/rtools44/x86_64-w64-mingw32.static.posix/lib -LD:/RCompile/recent/R/bin/x64 -lR
installing to d:/RCompile/CRANguest/R-devel/lib/00LOCK-optmatch/00new/optmatch/libs/x64
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* MD5 sums
packaged installation of 'optmatch' as optmatch_0.10.7.9001.zip
* DONE (optmatch)```

**Comment by benthestatistician** [comment]
Thanks @nullsatz!  I agree about targeting this week for a maintenance release. 

@josherrickson : It looks to me as though one cause of the first NOTE is Winbuilder's not finding rrelaxiv at the "repository" `https://errickson.net/rrelaxiv/`.  I'm guessing we just have to live with this (and thus with that NOTE), but if you think you see a way around it by populating your `drat` site with more package builds against R-devel, I'm willing to try my hand at making an intel Mac build against R devel.

**Comment by josherrickson** [comment]
That error only appears on winbuilder - it fails on all external links. We've not had an issue with that on CRAN as far as I know.

**Comment by josherrickson** [comment]
@nullsatz I'll take a look at everything on Wednesday and start bundling up for a release. @benthestatistician thoughts on version number? Any reason to bump more than the patch?

**Comment by benthestatistician** [comment]
Off the top of my head I'd say this is just a maintenance release, so just bump the patch number.  if you're willing to look through what we may have added as a part of submission prep, do tag me when the NEWS addition is ready.  Potentially that could suggest a different conclusion about the version number.

**Comment by josherrickson** [comment]
@nullsatz I'm going to close this issue. If you want to start up a new issue to track modernization/performance issues, go ahead.
