### ISSUE TITLE
port performance vignette to knitr from Sweave

### ISSUE THREAD

**Issue by nullsatz** [markmfredrickson/optmatch#239]
I couldn't find a pre-existing issue for this even though I was pretty sure there was one.

I produced a kind of messy port of the performance vignette to knitr and profvis.

The output is not perfect yet, but I'm able to produce an html document in RStudio.

I'm working in the branch `performance-knitr`

**Comment by benthestatistician** [comment]
How about making this a pull request?  Perhaps w/ a review request to Josh E.

**Comment by nullsatz** [comment]
Done! Thanks, Ben.

**Comment by benthestatistician** [comment]
Closing in favor of PR #240 240
