### ISSUE TITLE
`match_on`: `within` argument can be formula or sparse matrix

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#24]
The `master` branch `mdist` function uses formulas for two features that are not currently in the S4 branch, but could be:

1. Formula `x` args (i.e. the Mahalanobis distance method) used the vertical bar `|` to indicate blocking variables.
2. All methods included `structure.fmla = ~ X1 + X2 ...`. This was replaced with the `exclusions` argument.

Both blocking usages could be included by parsing the formulas and calling `exactMatch` with the valid formula (e.g. `Z ~ X1 + X2 `) and then adding this to the `exclusion` argument if any to create an updated `exclusions` argument. 

*Proposal*: change the `exclusions` argument name to `structure` and let it take either a formula or an `InfinitySparseMatrix`.

**Comment by benthestatistician** [comment]
If we can use pipes to communicate exact matching criteria, let's do that instead of this. (`within` will become a less frequently used argument, maybe used predominantly to communicate calipers.)

**Comment by markmfredrickson** [comment]
Issue #86 solved this with `strata` functions in the formula to `match_on.formula`.
