### ISSUE TITLE
fill.NAs returned objects may not have syntactically valid column names

### ISSUE THREAD

**Issue by jwbowers** [markmfredrickson/optmatch#39]
I think that R, strictly speaking, does not like column names with spaces. Mostly R is smart, but sometimes a data frame created with fill.NAs can cause trouble because of spaces in factor level names. This is funny because the spaces are allowed as output of model.matrix and most model fitting functions handle them fine during factor expansion. Yet, this from the help page for make.names:

```
 A syntactically valid name consists of letters, numbers and the
     dot or underline characters and starts with a letter or the dot
     not followed by a number.  Names such as ‘".2way"’ are not valid,
     and neither are the reserved words.
```

**Comment by markmfredrickson** [comment]
Cross linking to #104 which might to negate this issue.

**Comment by benthestatistician** [comment]
Closing: Mark provided one solution to the original problem;  one related issue arising in the thread, #83, has long since been dealt with. If we take up #104, perhaps we can reconsider this issue along the way.
