### ISSUE TITLE
fill.NAs should maintain class of LHS variable

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#47]
Consider

``` r
> library(survival)
> lung.alt = lung
> lung.alt[1,"age"] = NA
> sapply( fill.NAs(Surv(time, status) ~ age, data=lung.alt), class)
     time       age    age.NA 
"numeric" "numeric" "logical" 
```

In this context, it would be preferable for fill.NAs to have returned a vector of class "Surv", with attending structure, as "time":

``` r
> class(with(lung.alt, Surv(time, status)))
[1] "Surv"
```

Relevant to risk-set matching problems (but not to ordinary treatment-control matching).

**Comment by markmfredrickson** [comment]
Cross linking to #104, which might negate this issue.

**Comment by benthestatistician** [comment]
Two summers ago I abandoned my experiments with `Surv()` due to problems w/ matching on them that seem to be unrelated to optmatch.  Given that it didn't work for me, I don't see encouraging other users to do it.  

Not recognizing another setting where I'd be specifically interested in maintaining a special class attribute of the treatment variable, I'm going to close out this issue. (In fact, on another thread @josherrickson just talked me into supporting less than we currently support in the way of treatment variables.)  If/when work resumes on issue #104/ the `fillNAObject` branch, we might prefer design choices that keep our options open with regard to supporting something like this in the future.
