### ISSUE TITLE
`update` method for optmatch objects

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#54]
I'd like to be able to call update, with first argument an optmatch object, to re-create and execute a variant on the call to `fullmatch()` that created the object. (Implicitly, optmatch's generated with pairmatch() also involved a call to fullmatch(), so it's enough to recreate a call to fullmatch().  This will help with 2 things, one more immediate and one later:
1. In the immediate term, this will be an efficient way to recreate the min.controls, max.controls and mean.controls/omit.fraction arguments that were used the last time.
2. Later, after some more work is done at the solver and solver interface level, we'll work things out so that the matches and node prices deriving from a prior solution to the matching problem can be used as a starting point for the next one.  This may be implemented within `fullmatch` itself, or maybe not; in any event `update.optmatch` would implement it, and would be the preferred and user-recommended means of making use of this functionality.
3. When the user is providing ~~matches and~~ node prices from a previous matching problem, this method will have to check and regularize these inputs in various ways in order to use them as warm starts for a new call to the solver. (For example, if the user-provided distance is stored as double-precision then it'll have to be converted to integer before being provided to the solver, and the user-provided node prices will have to undergo a parallel conversion.) 
4. ~~We should preface these steps with checks to see (a) whether the provided matches coming from a solution to the old problem implicitly define a feasible flow (in the associated network) for the new problem; and, if so, (b) whether the user-provided node prices are in a complementary slackness relationship, vis a vis the new arc costs/matching distances, with the user-provided feasible flow.    The second of these checks should be performed using double-precision arc cost/match distance data, and double-precision node price data.  If both (a) and (b) are yeses, then we'll know there's no need to call the solver again at all; just return what was given (which will have been shown to be an optimal solution to the new problem).~~

**Comment by benthestatistician** [comment]
@adamrauh per our conversation today, I'm re-opening #54 in anticipation of you taking the lead on pushing it along in coming weeks.  (I also took the opportunity to add a detail to issue statement that hadn't occurred to be during the meeting but is a natural outgrowth of what was discussed there.)

**Comment by benthestatistician** [comment]
`update()` seems not to be working for pair matches: 

```r
pm1b  <- optmatch::pairmatch(pr ~ cap,
                           method="mahalanobis",#override Mahalanobis default
                           caliper=2,
                           data=nuclearplants)
update(pm1b, caliper=1.5) %>% summary()
## Error in `[[.default`(object, name, exact = TRUE) : 
##  subscript out of bounds
update(pm1b) 
## Error in `[[.default`(object, name, exact = TRUE) : 
##  subscript out of bounds
packageVersion("optmatch")
## [1] ‘0.9.10’
```

**Comment by josherrickson** [comment]
```
> pm1b  <- optmatch::pairmatch(pr ~ cap,
+                              method="mahalanobis",#override Mahalanobis default
+                              caliper=2,
+                              data=nuclearplants)
> update(pm1b, caliper=1.5) %>% summary()
Structure of matched sets:
1:1 0:1 
 10  12 
Effective Sample Size:  10 
(equivalent number of matched pairs).

Warning message:
In update.optmatch(pm1b, caliper = 1.5) :
  Distance given in update (7d1afd51b10e2a582b92c258ec45c32b) is different than distance used to generate fullmatch (88584dce730df309b6f12538c645f244).
> 
> packageVersion("optmatch")
[1] ‘0.9.10’
```

**Comment by benthestatistician** [comment]
Huh?  Here's the setup behind what I saw:

```r
 sessioninfo::session_info()
```

```

─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS Mojave 10.14.5        
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Detroit             
 date     2019-06-11                  

─ Packages ───────────────────────────────────────────────────────────────────
 ! package     * version  date       lib source        
   abind         1.4-5    2016-07-21 [1] CRAN (R 3.6.0)
   assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 R bigmatch    * 0.6.1    <NA>       [?] <NA>          
   cli           1.1.0    2019-03-19 [1] CRAN (R 3.6.0)
   crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
   digest        0.6.18   2018-10-10 [1] CRAN (R 3.6.0)
   iterators     1.0.10   2018-07-13 [1] CRAN (R 3.6.0)
 R itertools     0.1-3    <NA>       [?] <NA>          
   lattice       0.20-38  2018-11-04 [1] CRAN (R 3.6.0)
 R liqueueR      0.0.1    <NA>       [?] <NA>          
   magrittr    * 1.5      2014-11-22 [1] CRAN (R 3.6.0)
   MASS          7.3-51.4 2019-03-31 [1] CRAN (R 3.6.0)
   Matrix        1.2-17   2019-03-22 [1] CRAN (R 3.6.0)
 R mvnfast       0.2.5    <NA>       [?] <NA>          
   optmatch      0.9-10   2018-07-12 [1] CRAN (R 3.6.0)
   plyr          1.8.4    2016-06-08 [1] CRAN (R 3.6.0)
 R rcbalance     1.8.5    <NA>       [?] <NA>          
   Rcpp          1.0.1    2019-03-17 [1] CRAN (R 3.6.0)
   RItools       0.1-16   2018-06-19 [1] CRAN (R 3.6.0)
   sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
   SparseM       1.77     2017-04-23 [1] CRAN (R 3.6.0)
   survival      2.44-1.1 2019-04-01 [1] CRAN (R 3.6.0)
   svd           0.4.3    2019-04-05 [1] CRAN (R 3.6.0)
   withr         2.1.2    2018-03-15 [1] CRAN (R 3.6.0)
   xtable        1.8-4    2019-04-21 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

 R ── Package was removed from disk.
```

**Comment by benthestatistician** [comment]
Whatever the difference between my experience and Josh's, I was being routed through `update.default()`:

```
> traceback()
11: NextMethod("[[")
10: `[[.factor`(object, name, exact = TRUE)
9: object[[name, exact = TRUE]]
8: getElement(x, "call")
7: getCall.default(object)
6: getCall(object)
5: update.default(pm1b, caliper = 1.5)
4: update(pm1b, caliper = 1.5)
3: eval(lhs, parent, parent)
2: eval(lhs, parent, parent)
1: update(pm1b, caliper = 1.5) %>% summary()
```

**Comment by josherrickson** [comment]
After just having an offline discussion with @benthestatistician where I was arguing that this was a symptom of his system being malconfigured in some sense, I am now seeing the same bug:

```
> pm1b  <- optmatch::pairmatch(pr ~ cap,
+                              method="mahalanobis",#override Mahalanobis default
+                              caliper=2,
+                              data=nuclearplants)
> update(pm1b)
Error in `[[.default`(object, name, exact = TRUE) : 
  subscript out of bounds
```

**Comment by benthestatistician** [comment]
(Checked to see whether invoking R w/ `--vanilla` option would affect this for me.  It doesn't.)

**Comment by josherrickson** [comment]
It looks like the issue is having the `call` as an attribute instead of a slot. I think the next step is to figure out what changed to cause this to suddenly surface. It certainly wasn't a problem previously (as my comment 2 days ago shows). 

I think we can rule out an R version bump as the current version (3.6.0 came out in April). I thought it could be a package update or something, but that doesn't appear to be the case as on my laptop (which the following code was run on) has not had packages updated since end of May.

```
> library(optmatch)
> pm1b  <- pairmatch(pr ~ cap,
+                    data=nuclearplants)
> update(pm1b)
Error in `[[.default`(object, name, exact = TRUE) : 
  subscript out of bounds
> pm1b$call <- pm1b$call <- attr(pm1b, "call")
> update(pm1b)
   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S 
<NA>  1.2  1.2  1.4  1.4 <NA>  1.6 <NA>  1.6 <NA> <NA> <NA>  1.7  1.8 <NA> 
   T    U    D    V    E    W    F    X    G    Y    Z    d    e    f    a 
<NA>  1.9  1.7 <NA>  1.8  1.5  1.9 <NA> 1.10 <NA> <NA>  1.3 1.10  1.1  1.1 
   b    c 
 1.3  1.5 
```

**Comment by benthestatistician** [comment]
Weird.  To clarify implications of your comments, are we to understand that
you've got an explanation of how you first didn't get the error and later
did, the difference being in the version of R you were using?

Nice pinpoint of the cause of the trouble, though; seems like it should
admit a simple enough fix.

>

**Comment by josherrickson** [comment]
Exactly the opposite - I have no idea why it worked for me the first time but fails now. Nothing has changed regarding R version or packages between the two, yet it still fails.

The fix is quite simple, in `makeOptmatch`, store the call directly rather than as an attribute - I'm hesitant to just do that because I don't know why this suddenly is coming up now, given that the code in `update` was last touched in 2013, and the code in `makeOptmatch` that stores the call as an attribute was last touched in 2011. I checked R 3.0.0 source, and the function that's causing the issues, `getElement`, is identical, so I'm having a hard time believing that we never got this error before.

**Comment by benthestatistician** [comment]
Let's not rush into anything on this. I think it's likely that with the 1.0
release (cf #134) we'll want to push a new spec for the structure of what
full/pair match spit out, perhaps an S4 object; see notes in MCFSolutions
vignette, issue54-hinting branch.  Once we get to that, let's remind each
other to pay attn to the update problem we've been discussing over here.

>

**Comment by benthestatistician** [comment]
Chiming in again briefly to note a possible connection between (a) my earlier observation that `update.optmatch()` was not being invoked when I experienced this issue, and (b)  Josh's initial report that he couldn't reproduce the problem.  

We had bug report some time ago that turned out to turn on a method dispatch subtlety (#120).  The combination of (a) and (b) suggests to me that this is broadly the same sort of problem. (If we could convince `update()` to dispatch to `update.optmatch()` rather than `update.default()`, then the fact that the call is stored in an attribute rather than elsewhere wouldn't be a problem.)  In that case the problem was easy to fix once we had identified it; this time it was easier to figure out that our trouble had to do w/ message dispatch, but maybe it'll be a little trickier to figure it out from there.

**Comment by josherrickson** [comment]
That insight helped me figure it out. `update.optmatch` isn't currently being exported. Calling `update.optmatch(pm1b)` works fine.

The reason it wasn't an issue previously, and wasn't an issue for me a few days ago, was that when calling `devtools::load_all()`, internal functions are loaded as well. Calling `library(optmatch)` doesn't load internal functions.

I'm going to export `update.optmatch` in Master with the intention that we'll get it cleaned up and ready for the next maintenance release.

**Comment by benthestatistician** [comment]
:+1:

>

**Comment by josherrickson** [comment]
This is implemented, exported and tested.

**Comment by benthestatistician** [comment]
As I prepare to delete the branch titled "issue54-hinting", just noting here that it's currently up-to-date w/r/t branch proj1-nodeprices.
