### ISSUE TITLE
Check for sane data argument

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#56]
I recently passed a distance matrix as a `data` argument to `fullmatch`, with disastrous results. The problem was that `makeOptmatch` will go look in the `data` argument for the proper order of the output, including any units that have been dropped in the distance creation process. However, in this case, since there were only treated units on the rows of the distance matrix, `makeOptmatch` threw away all the control units. I think the smart thing to do would be to check the data argument to make sure that at least all of the units in the distance argument are present (more are OK), and return an error otherwise.

**Comment by benthestatistician** [comment]
While we're at this, let' fix the problem for `pairmatch` also.

**Comment by josherrickson** [comment]
Fixed.

No changes to `pairmatch` were necessary as the issue doesn't hit until after `pairmatch` calls `fullmatch`, so we can rely on the check in `fullmatch`.
