### ISSUE TITLE
Remove calculation of matched.distances from `fullmatch`; trash optmatch objects' matched.distances attributes

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#57]
We only need matched distances inside of `summary.optmatch`, as far as I can see. Then we can figure them on demand, via `matched.distances`. Otherwise let's quit taking the performance hit.

The will require modifying `summary.optmatch` so that it simply omits the matched distance report when it can't find any such attribute on the optmatch object (as opposed to just failing).

**Comment by benthestatistician** [comment]
Original version of issue raised the possibility of making fullmatch's matched.distances calculation optional. Now I think we should just get rid of it. Revising issue statement according.

**Comment by josherrickson** [comment]
Completed.
