### ISSUE TITLE
update.optmatch more testing

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#59]
Due to time constraints at present, update.optmatch() is not exported, but is in the code in an alpha-ish version. It works most of the time, but doesn't have a full test suite, particularly with respect to the new fullmatch(Z~X) style calls.

**Comment by benthestatistician** [comment]
From the #54 comment, here's a test we should have (currently fails/works inconsistently):


```r
data("nuclearplants")
pm1b  <- pairmatch(pr ~ cap, data=nuclearplants)
expect_is(update(pm1b, caliper=1.5) , "optmatch")
```

(And similarly for `fullmatch()`.)

**Comment by josherrickson** [comment]
One remaining issue is a warning related to a somewhat unexpected difference distance hash. I'll take a quick pass at it shortly, and failing that defer it to the next release.

**Comment by josherrickson** [comment]
This was addressed. While I'm sure there's scenarios I'm not anticipating, I'm comfortable releasing `update` with the current test suite.
