### ISSUE TITLE
Add two argument `[` method

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#63]
It would be nice to address the various sparse matrix implementations using the usual matrix style indexing (e.g., `mymatrix[1:10, 1:10]`). 

It can be done using the `subset` method, which ISMs implement:

https://gist.github.com/markmfredrickson/6157476

Right now, the base data type of ISM a numeric vector, so it has single dimension indexing (e.g. `mymatrix[1:10]` will return the first 10 cells in the matrix -- though the order is unspecified). Internally, we make use of this feature, so we can't entirely leave it behind. We'd need to overload the function to provide both or provide a two argument method specifically. This probably depends on whether `[` is a S3 or S4 generic.

**Comment by josherrickson** [comment]
I played around with this for a few minutes to see if I could get something into this release we're working on.

Differentiating between `m[1:10]` and `m[1:10,]` is tricky. The signature for `[` requires `x`, `i`, `j` and `drop`. Both versions above have `j = NULL`. I can't figure out another way to tell whether we're in `[x]` or `[x,]`. I've been trying to see R's `[` implementation but have had no luck yet, might have to pull the full source to find it.

That said, I'll be pushing a preliminary version up to optmatchExperimental shortly. With the exception of the above issue, I believe this performs as desired.

**Comment by benthestatistician** [comment]
After a couple minutes with this, my thoughts are:

- Here's the jist of how base R is maintaining the distinction between `m[1:10]` and `m[1:10,]` for data frames:
```r
head(base::`[.data.frame`)
                                                                      
1 function (x, i, j, drop = if (missing(i)) TRUE else length(cols) == 
2     1)                                                              
3 {                                                                   
4     mdrop <- missing(drop)                                          
5     Narg <- nargs() - !mdrop                                        
6     has.j <- !missing(j)           
```  
- (I was initially misled into thinking these functions weren't available, as `getMethod("[", "data.frame")` returns an error and `selectMethod("[", "data.frame"]` returns "Primitive".  Perhaps this is where Josh got held up when looking into this a few years ago.)
- Of the two forms, `m[1:10]` strikes me as dispensable.  But I wasn't immediately sure what we'd break if we got rid of it.

**Comment by josherrickson** [comment]
I've pushed up fixes over in optmatchExperimental. I believe this is completed; it supports all of `[X,X]`,`[X,]` and `[,X]`, and leaves `[X]` as before (returning a vector). The only thing that acts weird is `[X, drop = ...]` but I think that's such a bizarre edge case that it shouldn't matter (it ignores the `drop` argument more generally; requesting a single row or column always keeps dimension; which I assume is logic that Mark built into `subset.ISM`).

@benthestatistician Since this is such an old issue, just wanted to run it past you before I move it over here.

**Comment by josherrickson** [comment]
Implementation: [InfinitySparseMatrix.R](https://github.com/markmfredrickson/optmatchExperimental/blob/master/R/InfinitySparseMatrix.R)

Tests demonstation: [test.InfinitySparseMatrix.R](https://github.com/markmfredrickson/optmatchExperimental/blob/master/tests/testthat/test.InfinitySparseMatrix.R)

**Comment by benthestatistician** [comment]
Very very nice, Bravo!

What would you think about checking to see if the user has provided a drop
argument, if so throwing a warning about its being ignored?

>

**Comment by josherrickson** [comment]
Sure, can do.

**Comment by josherrickson** [comment]
Two potential outstanding issue:

- BISM's get converted to ISM's. Any objection?
- Substitution (e.g. `m[1:3,1:3] <- ...`) doesn't work. Do we want it to work? I've got no idea how to identify it for errors....

**Comment by benthestatistician** [comment]
No objection on the BISM to ISM conversion.

Nor about that replacement operator not working.  It would be nice to throw
an informative error, but I wouldn't be much help in figuring out how to
control that error message.  Does it throw an error message now?  If so,
I'd be inclined to see if we could live with it.

>

**Comment by josherrickson** [comment]
The current error is

```
> m2 <- match_on(pr ~ t2, data = nuclearplants[2:5,])
> m[1:2,1:2] <- m2
Error in m[1:2, 1:2] <- m2 : incorrect number of subscripts on matrix
> m[1,1] <- 3
Error in m[1,1] <- 3 : incorrect number of subscripts on matrix
```

I've really got no idea where to start on this - `traceback()` doesn't recognize this error, putting a `browser` in `[.InfinitySparseMatrix` doesn't trigger, and looking through the `[.data.frame` and `[.factor` code isn't giving any clues. Part of the complexity is that `[` is S3 generic, not S4.

It feels like the second of the examples above (where replacement replaces the `@.Data` with new values) is the most natural version (as opposed to the first which I was originally thinking of) and would be nice to implement. Something like `m[5,10:12] <- Inf` could be used.

**Comment by josherrickson** [comment]
Negative indexing doesn't work - need to fix that as well.

**Comment by benthestatistician** [comment]
Re tracking down the error, perhaps `options(error=recover)` is worth a
try?

I share your sense that replacement with a scalar or vector is a natural
first priority among the replacement ops. Perhaps negative indexing
should be a higher priority still.

>

**Comment by josherrickson** [comment]
Negative indexing is fixed (you probably saw a comment I posted then swiftly removed when I realized how easy to fix actually was).

**Comment by josherrickson** [comment]
No luck:

```
> options(error=recover)
> m[1,1] <- 1
Error in m[1, 1] <- 1 : incorrect number of subscripts on matrix
No suitable frames for recover()
```

**Comment by josherrickson** [comment]
Aha! `[<-.data.frame` is a separate function.

**Comment by josherrickson** [comment]
```
> a
       control
treated [,1] [,2]
   [1,]   20   40
   [2,]  Inf   10
> subset(a, subset = c(TRUE, TRUE), select = c(TRUE, FALSE))
       control
treated [,1]
   [1,]   20
```

Is this expected behavior? Should it return a 2x1 ISM with (20, Inf)?

**Comment by josherrickson** [comment]
Alright, replacement is implemented.

- `m[x] <- 1` is preserved.
- `m[x,x] <- ...` works as expected; RHS can be scalar (to replace all), vector (column-dominant like ISM, or matrix. 
- For a BISM; if all the replaced cells are within a group, it remains a BISM. If any of the replaced cells are cross-group, drop down to ISM.
