### ISSUE TITLE
`fullmatch` confused by objects inheriting from recognized s3 classes

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#64]
The below seems to be failing in version 0.9-0:
````r
library(brglm)
library(optmatch)
my.ppty.mod <- brglm(pr ~ date + t1 + t2 + cap + ne + ct + 
                     bw + cum.n + pt, data=nuclearplants)
fullmatch(my.ppty.mod)
Error in fullmatch.default(my.ppty.mod, data = nuclearplants) : 
  Invalid input, must be a potential argument to match_on
````
This despite the fact that `match_on` handles my.ppty.mod just fine.

I suspect this can be fixed without too much trouble, by adjusting the input-checking code at the top of `fullmatch.default`.  Perhaps it could benefit from the use of `inherits`?

**Comment by benthestatistician** [comment]
Reopening.  Pairmatch has a similar issue, which I suspect of being precisely the same problem: 

```{r}
> library(brglm)
Loading required package: profileModel
> bGlm = brglm(pr ~ . -(pr + cost), family=binomial, data=nuclearplants)
> pairmatch(bGlm)
Error in pairmatch.default(bGlm) : 
  Invalid input, must be a potential argument to match_on
```

I suspect that the same fix as was applied to `fullmatch` should work here also. See commit 71c3ffa comment I'm posting there presently.

**Comment by josherrickson** [comment]
Fixed.
