### ISSUE TITLE
Ease/provide guidance on stitching together subclass-specific distances

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#65]
Is it now possible for users to concatenate ISMs directly, forming an blocked ISM?  It seems to me that this shouldn't be too difficult to enable, if it's not already enabled.  If it is already enabled, the fact that I couldn't find my want to an example in the docs suggests that examples and/or links are in order. 

If there were also simple methods of extracting subproblems from a blocked ISM, together they might provide a relatively simple solution to #10.

**Comment by benthestatistician** [comment]
Earlier on this thread Mark suggested (roughly) that we implement this by a `diag()` method.  I argued against on the grounds that `base::diag()` has complicated semantics.  Chiming in briefly to note that the Matrix package's `bdiag()` may be a model for what we'd like to do here.

**Comment by josherrickson** [comment]
Was looking through old issues and came across this. I messed around with it for a few minutes here: https://gist.github.com/josherrickson/fe445df0c147d461f1be2a0cf7862ef0

It still needs cleanup and lots of special casing for dealing with different types of matrices but overall isn't that complicated.

This seems like something that would still be useful - any objections?

**Comment by josherrickson** [comment]
Getting close to pushing a version of this up. Any further suggestions no name? I'm not eager to extend `bdiag` as I think it would require a **Matrix** dependency. Can we just create a custom name? Right now it's called "`blockdiag`".

**Comment by josherrickson** [comment]
I pushed up this function with placeholder name, we can rename.

I looked through stratamatch but didn't see anything useful; they're mostly concerned with stratifying, not combining the strata.

I still think we should give it a unique name, as there is no generic that seems fitting.

Some ideas:
- "blockdiag" (current, don't love it)
- "stitch_distances"
- "make_BlockedInfinitySparseMatrix"
- "combine_distances"
- "merge_distances"

**Comment by benthestatistician** [comment]
Another two for the list:

- `dbind()` (geddit? `cbind()`/`rbind()`, but for distances/discrepancies)
- `as.BlockedInfinitySparseMatrix`/`as.BISM`. 

(If we went the latter route then we might want to think about accepting lists of ISMs, as well as multiple ISMs.)

**Comment by josherrickson** [comment]
I love `dbind`.

**Comment by josherrickson** [comment]
I added support for `list`s of distances as well. E.g. all the following will work:

```
dbind(ism1, ism2, ism3)
dbind(bism1, ism1) #creates an BISM with #groups(bism1)+1
dbind(list(ism1, ism2, ism3))
dbind(list(bism1, ism1), ism2, ism3, list(ism4, ism5)) #BISM with #groups(bism1)+5
```

Basically the input can be any distance that can be converted to an ISM; or a distance that is already a BISM; or lists of ISM-convertible distances and/or BISMs.
