### ISSUE TITLE
Use implicit data when `fullmatch` grabs environment

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#67]
We could probably eliminate this warning message (`xs` is a matrix):

```
> fm <- fullmatch(z ~ xs)
Warning message:
In fullmatch(z ~ xs) :
  Without 'data' argument the order of the match is not guaranteed
    to be the same as your original data.
```

**Comment by josherrickson** [comment]
Discussion with Ben offline.

The only cases where this warning should still be appearing are if an ISM (or similar) is passed to `fullmatch` without the data that generated the ISM. In all cases where a formula is passed, I believe that the situation the warning is highlighting will never occur.

@markmfredrickson, can you think of any other situations?

Assuming not, this essentially corresponds to moving the warning from inside `fullmatch.default` into `fullmatch.matrix`.

**Comment by josherrickson** [comment]
Per my last comment, this warning now only appears for matrices, ISMs and optmatch.dlist objects.

Ultimately, this doesn't address the issue of ~100 warnings popping up during `devtools::test()`.

**Comment by markmfredrickson** [comment]
The decision on warnings makes sense. The purpose here is to let people know that things like bare matrices/ISMs/etc. could return a vector in an arbitrary order. If we get the implicit data from the environment, we have the proper order.

**Comment by josherrickson** [comment]
I believe this issue is closable.
