### ISSUE TITLE
Adjust warning when only failures are in infeasible subgroup

### ISSUE THREAD

**Issue by josherrickson** [markmfredrickson/optmatch#69]
If a user has subproblems, some of which are only treatment or only control members, that gets seen as failure to match. Really, its just several unmatchable members (similar to a row/col of match with all Inf) and not a failure. (See email conversion "Fwd: A question regarding R package Optmatch")

**Comment by benthestatistician** [comment]
It appears that this has been fixed (probably a while back):
```{r}
library(optmatch)
library(survival)
data(nuclearplants)
with(nuclearplants, table(pr, interaction(pt,bw)))
##pr  0.0 1.0 0.1 1.1
##  0  16   2   3   1
##  1   7   1   0   2
```
Indicating that if you exact match on `pt` and `bw`, there's a subclass w/o treatment group members.  However, no warning here:
```{r}
fullmatch(pr~cap+strata(pt,bw), data=nuclearplants)
##   H    I    A    J    B    K    L    M    C    N    O    P    Q    R    S    T 
##1.10  1.4  1.2  1.4  1.4  1.7  1.6  1.7  1.6 1.10  1.7 1.10  1.7  1.8  1.6 1.10 
##  U    D    V    E    W    F    X    G    Y    Z    d    e    f    a    b    c 
## 1.9  1.7  1.2  1.8  1.9  1.9 1.10 1.10  1.7  1.4  1.3  1.3  1.1  1.1  1.3  1.1 
```

 @josherrickson, could you confirm that I'm not missing something, and close?

**Comment by josherrickson** [comment]
There does not appear to be a warning here, but your output doesn't look correct Ben.

With the latest master, I get the following


    > fullmatch(pr~cap+strata(pt,bw), data=nuclearplants)
        H     I     A     J     B     K     L     M     C     N     O     P     Q
    0.0.7 0.0.2 0.0.1 0.0.1 0.0.2 0.0.4 0.0.3 0.0.4 0.0.3  <NA> 0.0.4 0.0.7 0.0.4
        R     S     T     U     D     V     E     W     F     X     G     Y     Z
    0.0.5  <NA> 0.0.7 0.0.6 0.0.4 0.0.2 0.0.5  <NA> 0.0.6 0.0.7 0.0.7 0.0.4 0.0.2
        d     e     f     a     b     c
    1.0.1 1.0.1 1.1.1 1.1.1 1.0.1 1.1.1

N, S and W are the control members in the 0.1 subgroup and should not be matched. Why are they matched in your output?

**Comment by benthestatistician** [comment]
Good points, Josh. I think I inadvertently had optmatch 0.9-3 loaded instead of 0.9-5, with the consequence that the inclusion of `strata(pt,bw)` in the formula was adding `interaction(pt,bw)` to the Mahalanobis distance, rather than enforcing exact matching on them. When I rerun at the same machine but being sure to load optmatch 0.9-5, my output matches yours.

Closing, as I take it Josh has no other remembered concerns. (If you do, J, then pls reopen.)
