### ISSUE TITLE
`scores` should check its  "object" argument for non-NULL "subset" specifications & overwrite them

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#73]
As of this writing, inst/tests/test.scores.R has 
````{r}
pgscore <- lm(cost~cap + interaction(ct,bw), weights=t1, 
subset=(pr==0), data=nuclearplants)  
# This doesn't work without the newdata argument.
  expect_error(l5 <- lm(pr ~ cap + scores(pgscore), data=nuclearplants))
````

This is totally OK, but I think the ideally desirable behavior here would be to have `scores` soldier through without complaint, stripping off the 
````{r}
subset=(pr==0)
````
part of the call generating pgscore before updating it.  

No rush about implementing this. Rather, I'd be interested to hear comments about potential side effects.

**Comment by benthestatistician** [comment]
As @josherrickson and I have been discussing related issues, I'd like to propose a simple resolution to this issue.  if it looks OK to you, Josh, please implement and then close out the issue.

The resolution: if `scores` craps out after getting into its branch concerned with refitting after imputing NAs, then we throw an informative error intended to help the user circumvent the limitations of `get_all_vars` in our context. Specifically, we throw an error message suggesting to the user that she or he take care of the NAs in the data used to fit `object` before invoking `score`.  Something like "I found NAs in model.frame( deparse substitute blah blah) but was unable to refit the model after imputing them.  Try doing this manually, using fill.NAs() or another imputation routine, or restrict fit of deparse substitute blah blah to complete cases."  (Here deparse substitute blah blah" is a gesture to code to grab the user's name of the object fed to `scores`.)

**Comment by josherrickson** [comment]
Implemented in a4f2463.

Passing to Ben, please close or send back to me with updates to the actual error message produced.

**Comment by benthestatistician** [comment]
Two comments:
1. Could we arrange to have the error message reference the `object` argument in whatever way the user is referencing it?  Users will appreciate this.  That's what I meant to gesture to with "deparse substitute blah blah". One example of that, somewhat more complex than is seen here, is @nullsatz's function `missing_x_msg`, in optmatch/R/utliities.R.  
2. For the text in the `stop`, how about the following, or similar:   
> "Unable to address missingness in $OBJECT on the fly.\nTry dealing with NAs before the call to scores(), perhaps using fill.NAs()."

Thanks for the help here, @josherrickson.

**Comment by josherrickson** [comment]
Done. 

    > pgscore <- lm(cost~cap + interaction(ct,bw), weights=t1, subset=(pr==0), data=nuclearplants)
    > lm(pr ~ cap + scores(pgscore), data=nuclearplants)
    Error in scores(pgscore) :
      Unable to address missingness in pgscore on the fly.
    Try dealing with NAs before the call to scores(), perhaps using fill.NAs().

**Comment by benthestatistician** [comment]
Terrific, thanks!
