### ISSUE TITLE
Update `fmatch` error message to reflect actual max problem size that's in force

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#78]
If `fmatch` bombs out because it was given a problem with more arcs than the maximum problem size, its error message describes the max problem size as 1e7, event if it's been changed from that value.  See [this line](https://github.com/markmfredrickson/optmatch/blob/master/R/fmatch.R#L44) of R/fmatch.R.

**Comment by markmfredrickson** [comment]
I left the `stop` in, but added a note on how to disable the check.
