### ISSUE TITLE
Use of `$(shell)` in Makefile

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#79]
From the CRAN team:

> 'Writing R Extensions' warns against the use of this GNUism, but we see
> 
> AdaptiveSparsity/src/Makevars:PKG_LIBS=$(shell ${R_HOME}/bin/Rscript -e "Rcpp:::LdFlags()" ) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
> 
> optmatch/src/Makevars:MY_LAPACK_LIBS = $(shell $(REXEC) CMD config LAPACK_LIBS)
> optmatch/src/Makevars:MY_BLAS_LIBS = $(shell $(REXEC) CMD config BLAS_LIBS)
> optmatch/src/Makevars:MY_FLIBS = $(shell $(REXEC) CMD config FLIBS)
> 
> rotations/src/Makevars:PKG_LIBS = $(shell $(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()" ) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
> 
> Please correct it (use ``).
> 
> For optmatch, simply
> 
> PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
> 
> suffices.

**Comment by josherrickson** [comment]
I believe this may have been fixed with the combination of 81af8b5c and the move to devtools. @markmfredrickson can you confirm?

**Comment by markmfredrickson** [comment]
Looks like it.
