### ISSUE TITLE
Binary operations over ISMs

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#81]
Right now we implement the `Arith` group of operations for ISMs and vectors. It would be good to also implement the comparison and logic groups for both. The convention in the `Arith` operations is that the ISM is treated as if it were a column-major ordered dense matrix (where order is given by the `rownames` slot). This logic could get factored out into a helper function and then reused for arbitrary binary operations, such as comparisons and logical operations.

**Comment by benthestatistician** [comment]
Assigning this to Josh B, as he'll be working on the ISM class.  I don't know how important it is that we do this, so don't invest too much, unless Mark says otherwise; and feel free to revise or eliminate task, as appropriate.

**Comment by nullsatz** [comment]
Built the latest R-patched with memory profiling definitely enabled. Then got some interesting results as far as memory goes. Output of Rprofmem attached. Rprofmem implicates 'mapply' and the last 'match' in Ops by shear number of lines devoted to them in the output as does Rprof:

> source('~/src/test/DenseMatrix.R')
> source('~/src/test/InfinitySparseMatrix.R')
> size <- 500
> indexes <- rep(1:size, size)
> a <- new("InfinitySparseMatrix", runif(size * size), cols = indexes, rows = sort(indexes))
> Rprof('Rprof.out', memory.profiling=TRUE)
> b <- a + a
> Rprof(NULL)
> summaryRprof('Rprof.out', memory='both')
$by.self
              self.time self.pct total.time total.pct mem.total
"match"            3.74    73.05       3.74     73.05     171.5
"mapply"           1.16    22.66       1.30     25.39     327.6
"<Anonymous>"      0.14     2.73       0.14      2.73      40.9
"+"                0.08     1.56       5.12    100.00     517.4

$by.total
              total.time total.pct mem.total self.time self.pct
"+"                 5.12    100.00     517.4      0.08     1.56
"match"             3.74     73.05     171.5      3.74    73.05
"%in%"              1.76     34.38      93.0      0.00     0.00
"which"             1.76     34.38      93.0      0.00     0.00
"mapply"            1.30     25.39     327.6      1.16    22.66
"<Anonymous>"       0.14      2.73      40.9      0.14     2.73

$sample.interval
[1] 0.02

$sampling.time
[1] 5.12

Tried Hadley Wickam's lineprof, but couldn't get it to dig deeper than '+'. I think I would have to rewrite the "Ops" method as a plain R function. Not sure it's worth the time. I think Rprof and Rprofmem are already giving us the answer.

I'll start working on either tinkering with the "Ops" method as well as keeping rows and cols sorted in the ISM data structure.

**Comment by nullsatz** [comment]
Can't attach my Rprofmem.out file. Shoot.

**Comment by nullsatz** [comment]
Branch issue81 contains new C++ ISM binary operations.
make test passes

**Comment by markmfredrickson** [comment]
Looks good. I wonder if we can even do a little better. Right now, we calls to `match` to get ISMs that have the same names but in different orders to have the same IDs. We don't guarantee that ISMs have rows or columns in any specific order, so different matrix generation functions are free to do whatever they want.

For example, we could have two different representations of this matrix (which are conceptually the same graph):

```
> q
   C1  C2
T1  1 Inf
T2  2   4
> str(B)
Formal class 'InfinitySparseMatrix' [package "optmatch"] with 7 slots
  ..@ .Data    : num [1:3] 1 2 4
  ..@ cols     : int [1:3] 1 1 2
  ..@ rows     : int [1:3] 1 2 2
  ..@ dimension: int [1:2] 2 2
  ..@ colnames : chr [1:2] "C1" "C2"
  ..@ rownames : chr [1:2] "T1" "T2"
  ..@ call     : NULL
> str(C)
Formal class 'InfinitySparseMatrix' [package "optmatch"] with 7 slots
  ..@ .Data    : num [1:3] 4 1 2
  ..@ cols     : int [1:3] 1 2 2
  ..@ rows     : int [1:3] 2 1 2
  ..@ dimension: int [1:2] 2 2
  ..@ colnames : chr [1:2] "C2" "C1"
  ..@ rownames : chr [1:2] "T1" "T2"
  ..@ call     : NULL
```
What `B` calls column id 1 is what `C` calls column id 2 (and vice versa). Consequently, if we were to do `B + C`, [we would shuffle the data in `C`](https://github.com/markmfredrickson/optmatch/blob/issue81/R/InfinitySparseMatrix.R#L163) to be in the same order as `B`.

Given that we are also doing some sorting and shuffling at the C level, I wonder if this could also be dropped down a level.

Alternatively, if we made it a condition of the ISM data type that the rownames and colnames were always in alphabetical order, we wouldn't have to worry about this. But this is a larger task, and I don't want to hold up these patches if we decide to wait on the larger changes.

**Comment by benthestatistician** [comment]
At the moment I can't get the issue81 branch to compile on my mac.
````
$ make test
<...>
usr/bin/clang++ -I/opt/local/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/opt/local/include -I"/Users/bbh/Library/R/3.1/library/Rcpp/include"   -fPIC  -pipe -Os -arch x86_64 -stdlib=libstdc++  -c ism.cc -o ism.o
In file included from ism.cc:1:
In file included from ./ism.h:2:
In file included from /Users/bbh/Library/R/3.1/library/Rcpp/include/Rcpp.h:27:
In file included from /Users/bbh/Library/R/3.1/library/Rcpp/include/RcppCommon.h:61:
In file included from /usr/include/c++/4.2.1/iterator:69:
In file included from /usr/include/c++/4.2.1/ostream:44:
In file included from /usr/include/c++/4.2.1/ios:49:
In file included from /usr/include/c++/4.2.1/bits/basic_ios.h:43:
In file included from /usr/include/c++/4.2.1/bits/locale_facets.h:1538:
/usr/include/c++/4.2.1/bits/codecvt.h:217:35: error: too many arguments provided
      to function-like macro invocation
      length(state_type& __state, const extern_type* __from,
                                  ^
/opt/local/Library/Frameworks/R.framework/Resources/include/Rinternals.h:1138:9: note: 
      macro 'length' defined here
#define length(x)               Rf_length(x)
        ^
In file included from ism.cc:1:
In file included from ./ism.h:2:
In file included from /Users/bbh/Library/R/3.1/library/Rcpp/include/Rcpp.h:27:
In file included from /Users/bbh/Library/R/3.1/library/Rcpp/include/RcppCommon.h:61:
In file included from /usr/include/c++/4.2.1/iterator:69:
In file included from /usr/include/c++/4.2.1/ostream:44:
In file included from /usr/include/c++/4.2.1/ios:49:
In file included from /usr/include/c++/4.2.1/bits/basic_ios.h:43:
In file included from /usr/include/c++/4.2.1/bits/locale_facets.h:1538:
/usr/include/c++/4.2.1/bits/codecvt.h:217:13: error: expected ';' at end of
      declaration list
      length(state_type& __state, const extern_type* __from,
            ^
2 errors generated.
make[1]: *** [ism.o] Error 1
````
This against commit 383c7808500df3c248fa7ef3e19d3ef7bfa35e2b, and on a system as follows.  
````
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin12.5.0 (64-bit)

locale:
[1] C
````
Help/advice?

**Comment by nullsatz** [comment]
We may need to add something to our makevars for clang. I'll try to check
it out early this week.

**Comment by nullsatz** [comment]
I pushed a fix just now for Ben's issue on OSX.

The included header files need cleaning up after the conversion to Rcpp. We
should be including Rcpp.h and not most of the R header files like R.h
Rdefines.h and Rinternals.h

I'll try to take care of the clean up this week.

**Comment by nullsatz** [comment]
For R 2.15.2 we need to use Rcpp 0.10.5

I just pushed a compatibility fix for R 2.15.2 and Rcpp 0.10.5

Installed ok with latest R and Rcpp too, I think. Please let me know if you have any trouble on OSX.

**Comment by benthestatistician** [comment]
No trouble on OSX for me! R version 3.1.1 on OS 10.8.5 -- same setup that it wouldn't build on a few weeks back. Also compiled OK for me on RHL (the evalengin box).

**Comment by nullsatz** [comment]
I merged branch issue81 with the master branch and uploaded the result to winbuilder. Winbuilder build it with only 1 warning about me changing the maintainer (only so I could get the email).

So I merged the branch issue81 with the master and pushed it up to github. I'm closing this issue.
