### ISSUE TITLE
`match_on` should dispatch numeric method when it can't find its first argument

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#82]
We had a report from a user who was trying to get code along these lines to work:
```
data(nuclearplants)
d1 = match_on(cap, z=pr, data=nuclearplants)
```
Because `match_on` can't find `cap` at the moment it has to dispatch, this fails and throws an error ("Error in match_on<...>: object 'cap' not found").  

The premise of the issue title is that we can fix this problem, without causing others, by dispatching to the numeric method in this situation.  I can't think of a scenario where one of the other `match_on` methods (for bigglm's, formulas, functions, glms, InfinitySparseMatrix-es, or matrix-es) would want to look inside of the `data` argument to find its first argument, so it seems OK to let the numeric method handle this situation.  If you see unwanted side effects that I'm missing, do speak up. 

If we do handle the problem as I'm proposing to do, `match_on.numeric` should get a new error check at the top, to informatively identify the situation when the first argument just isn't to be found anywhere (perhaps because it was mistyped).

**Comment by benthestatistician** [comment]
It appears that @nullsatz set up the informative error message in the missing_x branch some months back.  I like what I see there - is it waiting on anything in particular before a merge back into master?

**Comment by nullsatz** [comment]
Just merged missing_x into master.
