### ISSUE TITLE
pipes in `match_on` formulas?

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#86]
In response to an aside from me, on the #82 thread @markmfredrickson suggested enabling usage like
```
match_on(pr ~ cap + date | pt, data = nuclearplants)
```
interpreting the material to the right of the pipe an `exactMatch` type restriction.  Starting up a thread here to discuss advantages and feasibility.

**Comment by nullsatz** [comment]
In the presence of pipes, missing_x_msg from R/utilities.R will need some elaboration.

**Comment by markmfredrickson** [comment]
Cross linking with #24.

**Comment by benthestatistician** [comment]
1. I think we should do this instead of (what now remains of) #24
2. In the interests of simplifying this task, let's assume to begin with that calipers are specified otherwise. Only blocking factors to the right of the pipe.

Then piping could work by assembling a blocking formula from the LHS of the formula that was given to `match_on`, joined by a `~` to the whatever is to the right of the pipe.  This blocking formula is then passed down to `exactMatch`.

**Comment by benthestatistician** [comment]
If, per #101, we're going to start encouraging the use of `strata` in propensity modeling formulas to specify exact matching variables, then maybe we should be doing the same in mahalanobis/Euclidean distances.  I.e., maybe we should introduce support for `strata` _instead of_ support for pipes.  

I lean this way myself, because I think I can make good use of the `strata` semantics in other PS related contexts.  But I'd welcome others' thoughts.

**Comment by josherrickson** [comment]
@benthestatistician With #101 finished, can this likewise be closed?

**Comment by benthestatistician** [comment]
While I think #101 was closed a little prematurely, the commit behind its closing suffices for this issue. 

 In any case, now that users can specify exact matching within the formulas passed directly to `match_on`, `pairmatch` or `fullmatch`, there's no need for pipes anymore.  Thanks again!
