### ISSUE TITLE
`match_on` NA handling

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#87]
9ccdf05 fixes bugs caused by NA removal in `model.frame`. There are a few other places in `match_on` methods that use `model.frame` with the default argument `na.action = na.omit`. What should the policy for `match_on` methods be?

**Comment by benthestatistician** [comment]
After some offline discussion/hearing from some frustrated users, I think the default policy should be `na.action=na.pass` (or similar), followed by recoding any resulting NAs in the ISM to `Inf`.  The end result, after user calls `fullmatch` or `pairmatch`, is that the unit in question will just go unmatched.

There's remaining question about whether the user should get some sort of warning about NAs having been kicked out. I think not; we have too many idle warnings as it is. 

On the other hand, maybe there are users out there who are in the habit of checking the `na.action` on fitted model objects to see if NAs got removed. We might consider adding an `na.action` attribute to the ISM and optmatch classes.  But let's not let pondering that stand in the way of accomplishing these changes to NA handling overall.

**Comment by markmfredrickson** [comment]
I've implemented this for the formula method, but I noticed there is an inconsistency with the GLM method that attempts to patch missingness. From the test code from the previous commit:

```
  d <- data.frame(z  = c(1,1,1,0,0),
                  x1 = c(7, 9, NA, -1, 4),
                  x2 = c(1, 0, 0, 0, 1))

  rownames(d) <- c("A", "B", "C", "y", "z")

  f <- function(method) {
    v <- as.matrix(match_on(z ~ x1 + x2, data = d, method = method))
    is.finite(v) & !is.na(v)
  }

  expectedM <- matrix(c(T, T, F, T, T, F), nrow = 3, dimnames = list(c("A", "B", "C"), c("y", "z")))
  
  expect_equivalent(f("mahalanobis"), expectedM)
  expect_equivalent(f("euclid"), expectedM)
  expect_equivalent(f("rank_mahal"), expectedM)

  ## now with glms
  v <- as.matrix(match_on(glm(z ~ x1 + x2, data = d, family = binomial)))
  x <- is.finite(v) & !is.na(v)
  expect_equivalent(x, expectedM)
```
The last tests fails because the NA's don't get propagated for the GLM method.

Is this the behavior we want? Even if inconsistent, it is probably preferred.

**Comment by benthestatistician** [comment]
I'm OK with these two methods handling NAs differently. There may be
something better on the Mahalanobis/Euclidean side than casewise deletion -
impute to linear regression prediction of missing field from non-missing
fields, perhaps - but I take that to be a project for another day.

Something that _may_ make sense as an add-on: add an na.action slot or
attribute to the ISM class, along with or in anticipation of an `na.action`
attribute for optmatch objects.

**Comment by markmfredrickson** [comment]
In order to avoid confusing the issue, I'm going to close this ticket. If-when we want `na.action` slots, we can draw up guidelines.
