### ISSUE TITLE
`demo/optmatch.r` is out of date and has errors

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#88]
This file has fallen out of date with the rest of the package. In addition to relying on `mdist` and some older styles of distance creation, it runs into an error attempting to compare two different matches.

Do we want to keep this file? If so, we should update it.

**Comment by benthestatistician** [comment]
Let's disable the demo, at least for the time being.

**Comment by markmfredrickson** [comment]
I've left the file in place if we ever want to update it, but it is no longer included in the `.tar.gz`.
