### ISSUE TITLE
Documentation on using optmatch with SAS and Stata

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#89]
I recently worked through a problem with a user where he did his matching in R, but wanted to export the optmatch object to SAS. The default way of marking groups is to use lexicographical ordering ("1.1", "1.2", ... "1.9", "1.10", ...). When imported into SAS, the data was assumed to be numeric and "1.1" and "1.10" were treated as the same value. The solution was to export the match using `as.numeric`.

We should create a wiki page or include it in a vignette.

**Comment by josherrickson** [comment]
The shortcourse we taught showed me the need for a specific vignette addressing this, 0263d699 introduces a basic version. It may need to be cleaned up, but the idea exists. Whenever we push the next version up to CRAN, this should appear on our CRAN page.

**Comment by benthestatistician** [comment]
Terrific! thanks, @josherrickson.
