### ISSUE TITLE
error identifying infeasible problems

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#92]
At the beginning of `.fullmatch.with.recovery`, decision as to whether to trigger recovery is based on whether
````
(mxctl.r * dim(d.r)[1] >= prod(dim(d.r)[2], omf.r, na.rm=TRUE)
````
is `TRUE`.  I think the criterion should instead be
````
(mxctl.r * dim(d.r)[1] >= prod(dim(d.r)[2], 1-omf.r, na.rm=TRUE)
````

**Comment by josherrickson** [comment]
Fixed in 59085225.
