### ISSUE TITLE
C code improvement

### ISSUE THREAD

**Issue by nullsatz** [markmfredrickson/optmatch#95]
Since we have adopted Rcpp to help with binary ISM ops, we could update the rest of the C code to use the Rcpp api. This would reduce the raw lines of code, help reduce the meaningless C boilerplate, and improve readability.

I would also like to introduce doxygen comments in the C code even if we are not using it to produce external docs.

**Comment by benthestatistician** [comment]
Make sense to me. I imagine there may be a performance hit, but if so then it would likely be modest? 

In any case, if Mark agrees then I say go for it.

**Comment by markmfredrickson** [comment]
Sounds good to me.
