### ISSUE TITLE
Drop used levels after subsetting

### ISSUE THREAD

**Issue by markmfredrickson** [markmfredrickson/optmatch#96]
Right now, when we subset an an `optmatch` object, the updated factor has "ghost" levels that hang around:

```
> nlevels(fm5)
[1] 7
> nlevels(fm5[1:2])
[1] 7
```
The solution is as simple as calling `factor` on the match object before we return it.

```
> nlevels(factor(fm5[1:2]))
[1] 1
```

**Comment by benthestatistician** [comment]
In principle, `[.optmatch` takes a `drop` argument.  I'm not certain, but suspect it that it's not doing anything with it as of now.  I'd support (a) fixing that bug, so that it actually drops levels if you tell it to; and (b) in this context having `drop` default to `TRUE`, counter to settings for other `[` methods.

**Comment by markmfredrickson** [comment]
Then never mind. This behavior is consistent with the underlying factor behavior, so we should keep that.

**Comment by benthestatistician** [comment]
Checking just now, it appears that `[.optmatch` does listen to `drop` arguments:
````
> levels(pm1[1:10])
 [1] "1.1"  "1.10" "1.2"  "1.3"  "1.4"  "1.5"  "1.6"  "1.7"  "1.8"  "1.9" 
> levels(pm1[1:10, drop=T])
[1] "1.1" "1.2" "1.4" "1.5" "1.6"
````
So, no bug per se.  

For future reference, I'm still open to making `TRUE` the default of `drop`.  Since Mark doesn't seem eager to do that, though, I'm going to close without changing anything.

**Comment by josherrickson** [comment]
Just posting a bit of sample code for an problem I ran into, in case anyone comes across this issue with the same problem.

If you have a match as a column in a data.frame, and subset the entire data.frame, you can't pass `drop=TRUE` into the whole data.frame and expect it to work. You have to `drop` on the actual optmatch object. I suppose that should have been obvious to me, but it took me a minute to realize my error. E.g.

    data
    data$match <- fullmatch(...)
    dsub <- data[1:10,,drop=TRUE] # dsub$match will not drop empty levels.

    dsub$match <- data$match[1:10,drop=TRUE] # Now it will drop empty levels.

**Comment by benthestatistician** [comment]
I wondered if maybe changing to the `[.optmatch` default from `drop=FALSE` to `drop=TRUE`, as considered earlier in this thread, would fix the problem Mark reports.  So I tried it out.  Unless I've made a scoping mistake, the answer appears to be no, that wouldn't fix the problem, as seen in the attached.  

To conclusively rule out the possibility of a scoping problem, one would want to test these examples after rebuilding the package after making this change, something I didn't do.   From my perspective, this is enough to justify leaving this issue closed (for now). 
[i96.txt](https://github.com/markmfredrickson/optmatch/files/44128/i96.txt)

**Comment by josherrickson** [comment]
This is related to [Issue 1 in optmatchExperimental](https://github.com/markmfredrickson/optmatchExperimental/issues/1). When using `drop=TRUE`, `matched.distances` attribute is not truncated appropriately.

    > data(nuclearplants)
    > f1 <- fullmatch(pr ~ cost, data=nuclearplants)
    > f2 <- f1[f1 %in% c("1.6", "1.2")]
    > f3 <- f1[f1 %in% c("1.6", "1.2"), drop=TRUE]
    > length(levels(f1))
    [1] 10
    > length(levels(f2))
    [1] 10
    > length(levels(f3))
    [1] 2
    > length(attr(f1, "matched.distances"))
    [1] 10
    > length(attr(f2, "matched.distances"))
    [1] 10
    > length(attr(f3, "matched.distances"))
    [1] 10

This caused a speed issue related to `mlm` in the issue I linked above. I'm not sure if this is something we want to overall fix, so not re-opening next.
