### ISSUE TITLE
When updating, `scores` to use `fill.NAs(formula(object), data=model.frame(object))`

### ISSUE THREAD

**Issue by benthestatistician** [markmfredrickson/optmatch#97]
Current implementation is a little different than what I had in mind.

**Comment by benthestatistician** [comment]
Not necessarily directly relevant to this issue, but potentially helpful for use with `scores`. I noticed that for functions called within a formula that may be used for prediction, one is encouraged to supply a `makepredictcall` method.  E.g., `scale`, `poly`, `ns`.  See help page for `makepredictcall`,
````
> ?SafePrediction
````

**Comment by josherrickson** [comment]
The `bigglm` class's version of `update` is a bit wonky; it looks like instead of refitting the model with the modified whatever, it only allows adding additional observations to the model. @markmfredrickson feel free to correct me if I've got that wrong.

@benthestatistician How do you want `scores.bigglm` to proceed? Should it simply skip the first stage (updating the object after imputation)?

**Comment by benthestatistician** [comment]
@josherrickson, my read of what `update.biglm` is doing concurs with yours.


As to what to do, my preference would be to refit the model with modified
data and formula, so that from the perspective of the optmatch user
`scores` has consistent behavior.  If that turns out to be tricky, though,
feel free to instead give the user an informative error message (indicating
what she should do by hand) and park your notes on the problem in the issue
queue (and, if appropriate, park code in a branch, w/ commit message
referencing the issue queue comments.

Side-note: did you consider calling `update.default` rather than
`update`/`update.biglm`?

**Comment by josherrickson** [comment]
I ended up with the second option; when using `biglm`, if the data is not complete, it throws a warning about imputing beforehand, and continues without imputation on the first stage.

**Comment by josherrickson** [comment]
This is implemented.

For the record, the way scores now works is via two steps. First, it (if needed) mean-imputes into the data which generated `object`, then refits `object`. Second, it (if needed) mean-imputes into `newdata`, whether `newdata` is explicitly given or is created automatically.

As stated before, `scores.bigglm` skips that first step.

There is also the remote possibility that a user creates several objects without `data` attached to them (e.g., the first test in test.RItools.R), the first stage will fail. If this happens, the first stage imputation is skipped, after a warning to the user that they should manually perform imputation.
